### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by guydepauw** [proycon/LaMachine#1]
If you want to go the docker-route on Ubuntu 14.04, the apt-get command should be

apt-get install docker.io

because of http://stackoverflow.com/questions/27978324/why-install-docker-on-ubuntu-should-be-sudo-apt-get-install-docker-io

**Comment by proycon** [comment]
Ah thanks! I didn't realize, I'll correct it!

**Comment by guydepauw** [comment]
Geweldig werk trouwens, LaMachine!

groetjes

Guy
