### ISSUE TITLE
Error during building of docker image

### ISSUE THREAD

**Issue by jkaan** [proycon/LaMachine#10]
For a project I'm working on, I need to create a slightly modified version of this project.

Therefore I'm running `docker build` to create the customized version of the project. For a few weeks now it was working fine up until today where the installation of libfolia fails. The error message that is shown is the following:

![screen shot 2016-05-10 at 15 27 18](https://cloud.githubusercontent.com/assets/3824068/15148007/bbbf1292-16c3-11e6-9f6f-ae6502a085e3.png)

The first thing I did was to check if there were any updates to this package, but there weren't. I also checked out a fresh copy of this project and tried to build the docker image again. I keep getting the same error message.

Do you have insights on this issue?

**Comment by proycon** [comment]
Thanks for the report! I managed to reproduce it indeed and we're looking into it. My guess is that Boost recently got upgraded to a new version in Arch Linux (which the LaMachine docker version uses), and this seems to cause some incompatibility now. We'll look into it!


Reproduces locally (Arch) in virtualenv context:
```
g++ -DHAVE_CONFIG_H -I. -I..  -I../include  -std=c++0x -g -O3  -g -O2 -I/usr/include/libxml2 -I/usr/include  -fopenmp -I/home/proycon/lamachine.stable/include -MT folialint.o -MD -MP -MF .deps/folialint.Tpo -c -o folialint.o folialint.cxx
mv -f .deps/folialint.Tpo .deps/folialint.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=c++0x -g -O3  -g -O2 -I/usr/include/libxml2 -I/usr/include  -fopenmp -I/home/proycon/lamachine.stable/include   -o folialint folialint.o libfolia.la -L/home/proycon/lamachine.stable/lib -lticcutils -L/usr/lib  -licui18n -licuuc -licudata   -licuio  -lxml2 
libtool: link: g++ -std=c++0x -g -O3 -g -O2 -I/usr/include/libxml2 -I/usr/include -fopenmp -I/home/proycon/lamachine.stable/include -o .libs/folialint folialint.o  ./.libs/libfolia.so -L/home/proycon/lamachine.stable/lib -L/usr/lib64 -L/usr/lib /home/proycon/lamachine.stable/lib/libticcutils.so -lbz2 -ltar -lboost_regex -licui18n -licuuc -licudata -licuio -lxml2 -fopenmp -Wl,-rpath -Wl,/home/proycon/lamachine.stable/lib
/home/proycon/lamachine.stable/lib/libticcutils.so: undefined reference to `boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
/home/proycon/lamachine.stable/lib/libticcutils.so: undefined reference to `boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
Makefile:677: recipe for target 'folialint' failed
```

**Comment by proycon** [comment]
Ok, I have good news and bad news.. The good news is that it's not an error on our side but a problem in the ``boost`` package for Arch Linux (which LaMachine builds upon for Docker and the VM). The bad news is that we therefore have to wait for others to fix it.

The bug and solution to it are already known (reported three days ago, see https://bugs.archlinux.org/task/49248) and will hopefully be fixed by the package maintainers soon. As soon as they release a new boost package, the issue should dissappear.

(original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1331983 )

**Comment by jkaan** [comment]
Thanks for the fast response!

In the meantime I'll just extend the `proycon/lamachine` docker image.

**Comment by proycon** [comment]
The Arch Linux packages have been updated by the maintainers, the issue should now be fixed (tested locally).
