### ISSUE TITLE
Too many open files / updating matplotlib

### ISSUE THREAD

**Issue by antalvdb** [proycon/LaMachine#103]
Found existing installation: matplotlib 2.2.2
    Uninstalling matplotlib-2.2.2:
      Successfully uninstalled matplotlib-2.2.2
  Rolling back uninstall of matplotlib

:stderr: Could not install packages due to an EnvironmentError: [Errno 23] Too many open files in system: '/Users/antalb/Software/stable/lib/python3.6/site-packages/matplotlib/backends/backend_tkcairo.py'

PLAY RECAP ****************************************************************************************************************************
stable                     : ok=76   changed=31   unreachable=0    failed=1

**Comment by proycon** [comment]
Hmm, I'm not sure what the cause of too many open file handles is here, it could be anything on the system (unrelated to the LaMachine update). Was there anything big in particular running? Can you reproduce it, say, after a reboot?

**Comment by antalvdb** [comment]
No, I now bump into another error (I'll make a new issue)
