### ISSUE TITLE
when Python version changes, LaMachine should autodetect this

### ISSUE THREAD

**Issue by antalvdb** [proycon/LaMachine#105]
[lamachine-stable-20180720_210437.log](https://github.com/proycon/LaMachine/files/2215132/lamachine-stable-20180720_210437.log)

**Comment by antalvdb** [comment]
got the exact same error on my other Macbook

**Comment by proycon** [comment]
Hmm, odd.. The ``python3-boost`` homebrew package does seem to be installed, judging by the log. But there is no ``/usr/local/opt/boost-python3/lib/libboost_python36.dylib`` on your system? Did the library change name perhaps? What files do you find in that directory?

**Comment by antalvdb** [comment]
all Python 3.7 files

(stable) antalb@MacBook-Pro-3:bp-som$ ls /usr/local/opt/boost-python3/lib/
libboost_numpy37-mt.a		libboost_python37-mt.a
libboost_numpy37-mt.dylib	libboost_python37-mt.dylib
libboost_numpy37.a		libboost_python37.a
libboost_numpy37.dylib		libboost_python37.dylib

**Comment by proycon** [comment]
Ah! So the homebrew Python version upgraded in the meantime!  I'd recommend starting with a completely fresh LaMachine virtualenv then.

**Comment by proycon** [comment]
I should in fact proably add some kind of Python version detector to LaMachine to inform the user about this...

**Comment by antalvdb** [comment]
OK, that works.
