### ISSUE TITLE
Locale in Docker is wrong

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#107]
As reported by @willstout in LanguageMachines/PICCL#39, the locale in LaMachine Docker erroneously defaults to POSIX whilst it should be an explicit ``en_US.UTF-8`` locale as forced in the other flavours of LaMachine as well.

**Comment by willstout** [comment]
I updated LaMachine just now (25GBs wow!) and typed `locale` into it and still got

```
lamachine@83e8bff017b1:/$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
lamachine@83e8bff017b1:/$
```

(I tested `locale ` in my git console app and got all UTF-8 just to be sure my locale didn't start as POSIX)

**Comment by proycon** [comment]
True, the update is not yet released into the stable LaMachine nor Docker Hub. I have to fix a few more things before the next release later this week.

**Comment by willstout** [comment]
Ahh, I saw ready and thought it might be good to go. My bad!

**Comment by proycon** [comment]
(released now)
