### ISSUE TITLE
frogwrapper.py seems to be making a wrong assumption about location of the frog config files

### ISSUE THREAD

**Issue by artm** [proycon/LaMachine#11]
We're trying to use frog via clam. When starting the project it dies with the following in the `error.log`:

```
[CLAM Dispatcher] Adding to PYTHONPATH: /usr/lib/python3.5/site-packages/clam/config
[CLAM Dispatcher] Started CLAM Dispatcher v2.1 with clam.config.frog (2016-05-19 14:19:52)
[CLAM Dispatcher] Running python3 "/usr/lib/python3.5/site-packages/clam/wrappers/frogwrapper.py" "/usr/bin/" "/clamdata/frog.clam/projects/anonymous/test1/clam.xml" "/clamdata/frog.clam/projects/anonymous/test1/.status" "/clamdata/frog.clam/projects/anonymous/test1/output/" > "/clamdata/frog.clam/projects/anonymous/test1/output//log"
[CLAM Dispatcher] Running with pid 31 (2016-05-19 14:19:52)
frog 0.13.3 (c) CLTS, ILK 1998 - 2016
CLST  - Centre for Language and Speech Technology,Radboud University
ILK   - Induction of Linguistic Knowledge Research Group,Tilburg University
based on [ucto 0.8.4, libfolia 1.0.1, timbl 6.4.7, ticcutils 0.11, mbt 3.2.15]
unable to read configuration from /usr/bin/../etc/frog/frog.cfg
failed to read configuration from '/usr/bin/../etc/frog/frog.cfg' !!
Did you correctly install the frogdata package?
frog-:fatal error: init failed
Processing 9851.txt...
    DocID from filename: 9851
Invoking Frog
[CLAM Dispatcher] Process ended (2016-05-19 14:19:53, 0.401692s) 
[CLAM Dispatcher] Removing temporary files
[CLAM Dispatcher] Status code out of range (256), setting to 127
[CLAM Dispatcher] Finished (2016-05-19 14:19:53), exit code 127, dispatcher wait time 0.39999999999999997s, duration 0.40246s
```

As far as I can see, the frogwrapper script assumes that `/etc/frog` folder can be reached one level above the `/usr/bin` (so it would be `/usr/etc/frog`), but there isn't any there. There is `/etc/frog` under the container root though. It seems like frogwrapper expected frog to be in something like `/usr/local/` with the binary in `/usr/local/bin` and configuration in `/usr/local/etc/frog`?

**Comment by artm** [comment]
after symlinking `/etc` into `/usr` the processing runs. The output is empty, but at least it gets made so we can debug further.

**Comment by artm** [comment]
(note: the output was empty due to "desired filename" being rejected when producing xml output, reuploading under an better name we now have output, so the above workaround did help)

**Comment by proycon** [comment]
It indeed seems to want to read from ``/usr/etc/frog`` although indeed they are in ``/etc/frog``. This is with the docker version of LaMachine I gather? Sounds like a configuration bug indeed.

**Comment by artm** [comment]
Yep, that was in docker

**Comment by spawn-guy** [comment]
i think i'm at the same current state of our problems.
@artm can you explain a bit more what needs to be done to make this thing work?

in my case - the `/etc/frog` does not exist at all.

**Comment by proycon** [comment]
The configuration moved in the latest Frog release, it is indeed now in ``/usr/share/`` instead of ``/etc/``. What does your ``error.log`` say?

**Comment by spawn-guy** [comment]
@proycon the error is exactly the same. it looks for cfg in `/usr/bin/../etc/frog/frog.cfg`
linking one file - fixed one step,.. but now it couldn't find the `frog.filter`

i'm in a process of relinking
```
mkdir -p /usr/etc
ln -s /usr/share/frog/nld /usr/etc/frog
```

**Comment by spawn-guy** [comment]
HURRAYY!!!
```
 <status code="2" message="Done" completion="100" errors="no" errormsg="">
        <log time="09/Mar/2017 15:21:42" completion="100">Done</log>
        <log time="09/Mar/2017 15:21:35" completion="0">Processing dutch.txt...</log>
        <log time="09/Mar/2017 15:21:35" completion="0">Starting...</log>
    </status>
```

**Comment by proycon** [comment]
Hmm.. glad you got it working! But we'll have to dive into the issue deeper then, because manually linking shouldn't be necessary of course.

**Comment by proycon** [comment]
Okay, I think I fixed it now. Please reopen if you still experience issues.
