### ISSUE TITLE
Frog as a service in Docker

### ISSUE THREAD

**Issue by timoveldt** [proycon/LaMachine#112]
In a previous release I was able to run Frog in server mode and use it as a "service". In the latest Docker image I can run small projects, but I cannot seem to get the server mode up and running anymore. The documentation (there was a specific example of a commandline call to run Frog in this way if I recall correctly). 

How can I use this feature?

The original call was something like this:
`docker run -p 10000:80 proycon:lamachine:latest frog -S 80`

**Comment by timoveldt** [comment]
I just tried it again and apparently frog fails to listen at port 80. I ran it at port 6000 and it started an actual server once (the previous attempts never started a server). However when restarting, the container exits without running a frog server. I've used the following command:
` docker run -it -p 10090:6000 proycon/lamachine:latest frog -X -S 6000`

**Comment by proycon** [comment]
port 80 is a privileged port typically, you need root to open it; higher ports such as 6000 should indeed work fine and are the better choice in such scenarios. 

As to it not running on restart, are you sure the previous container is not still running and hence the port is blocked? (check with ``docker ps``)

**Comment by timoveldt** [comment]
I fiddled around a bit longer and I seem to be up and running now with the following command:
`docker run -it -p 10090:10090 proycon/lamachine:latest frog -X -S10090`

Using port 6000 it seems that something is unstable on my system. The logs of the container don't show the expected logging (see below) and the container stops after a few seconds.

> frog-:Listening on port 6000

**Comment by proycon** [comment]
Good that you got it working, closing this issue then. I can't really explain why 6000 gave problems.
