### ISSUE TITLE
How do we run TensorFlow from LaMachine?

### ISSUE THREAD

**Issue by willstout** [proycon/LaMachine#113]
I'm trying different keywords but none seem to pull anything up. What word do I type?

**Comment by willstout** [comment]
I'm just trying to see the help contents of tensorflow, something I imagine I would find by typing something like `tensorflow --help`. 

Also `import tensorflow` gave me the error 

```
lamachine@54ddfdeb3371:/$ import tensorflow
import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/358.
```

Perhaps I'm not understanding the python interpreter

**Comment by proycon** [comment]
You can't run in it in the shell like that; it's a Python module (type ``python`` first to start the interpreter), but I think you're best of studying the tensorflow documentation at https://www.tensorflow.org/ .
