### ISSUE TITLE
Tesseract German Fraktur package missing in Ubuntu 18.04 (Bionic)

### ISSUE THREAD

**Issue by marijnschraagen** [proycon/LaMachine#117]
When trying to install PICCL on Ubuntu 18.04 using `lamachine-update --edit` and uncommenting the `- piccl` line, the installation fails because the package `tesseract-ocr-deu-frak` is not available.

Indeed this package has been removed from Ubuntu 18.04 (see https://launchpad.net/ubuntu/bionic/amd64/tesseract-ocr-deu-frak). It was still available in 17.10.

Log file of the installation: [lamachine-lmenv-20181002_113704.log](https://github.com/proycon/LaMachine/files/2437404/lamachine-lmenv-20181002_113704.log)

Note that this was an update of LaMachine, the environment itself (including all previously installed tools) works fine.

**Comment by proycon** [comment]
Ah! They removed it? Thanks for the report!

**Comment by proycon** [comment]
It's not merged into the master branch yet, I have a few other things to fix and test before that, after that you can just do ``lamachine-update``. Hopefully I can do a new release tomorrow.

(If you really don't want to wait you can clone this repo, switch to the develop branch and bootstrap a new LaMachine, but the develop branch might break at any point :) )

**Comment by proycon** [comment]
Sorry it took a bit longer because of the other issues, it's released now!

**Comment by marijnschraagen** [comment]
This bug is unfortunately still present in v2.4.2.

**Comment by proycon** [comment]
Hmm, strange..I tried explicitly excluding it now for Ubuntu 18.04 and up, can you see if that works?

**Comment by marijnschraagen** [comment]
Now I get this error:
```

From https://github.com/proycon/LaMachine
   57795e1..2db11be  master     -> origin/master
   ca96af8..eaaa906  develop    -> origin/develop
Updating 57795e1..2db11be
Fast-forward
 roles/piccl/tasks/main.yml | 9 +++++----
 1 file changed, 5 insertions(+), 4 deletions(-)
Using /home/marijn/prog/lmenv/src/LaMachine/ansible.cfg as config file
SUDO password: 
ERROR! conflicting action statements: include_role, package

The error appears to have been in '/home/marijn/prog/lmenv/src/LaMachine/roles/piccl/tasks/main.yml': line 26, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: Installing optional global dependencies for PICCL
      ^ here

```

**Comment by proycon** [comment]
Sorry, I had messed something up indeed, should have been fixed already in the meantime

**Comment by marijnschraagen** [comment]
Solved now, the installation works (and Tesseract seems to be running fine as well). Just a small question: does this mean that it is no longer possible to OCR German Fraktur? Not that I was planning to do that, but just in case.

**Comment by proycon** [comment]
Yeah, unfortunately. We might have to stop relying on the distribution for tesseract and compile it all from within LaMachine to remedy this.
