### ISSUE TITLE
Failed building wheel for uwsgi

### ISSUE THREAD

**Issue by pebbe** [proycon/LaMachine#118]
When I try to install on the stable version of Debian, I get `Failed building wheel for uwsgi`

See: [lamachine2.txt](https://github.com/proycon/LaMachine/files/2437648/lamachine2.txt)

**Comment by kosloot** [comment]
The missing types are defined in libpcap, so it seems.
No idea why this pops up now...

**Comment by proycon** [comment]
That is strange indeed, I haven't seen this before. Debian stable is the default for our VM and docker builds and those seem to go fine. I'll do some extra tests to see if I can reproduce this..

**Comment by pebbe** [comment]
It still fails. I tried to install uwsgi in the normal way, not in LaMachine, and it fails with the same error.

It looks like `uwsgi.h` is including `/usr/include/x86_64-linux-gnu/sys/capability.h`, but it should include `/usr/include/sys/capability.h`. This looks like a bug in the configuration of uwsgi. I will report an issue there.
