### ISSUE TITLE
Installation of LaMachine on Mac OS (Sierra, 10.12.6) failed

### ISSUE THREAD

**Issue by grammaticalization** [proycon/LaMachine#124]
Hi, 
I have tried installing LaMachine on my Mac several times but failed. The package asks for sudo rights although I am using my admin account. It is not possible to install "pip" and I get a "fatal error" every time:
touch: x: Permission denied
================ FATAL ERROR ==============
An error occurred during installation!!
Directory /Users/Shared/install is not writable for the current user! Run the bootstrap somewhere where you can write!
===========================================
bootstrap.sh: line 87: error: Permission denied
Can you tell me what is wrong? Thanks!

**Comment by proycon** [comment]
Sorry for the delay, this issue escaped my attention it seems. It seems you are running the LaMachine bootstrap in a directory where you can not write? What happens if you simply do a ``cd`` before running so you switch to your home directory?
