### ISSUE TITLE
New tool installation takes very long

### ISSUE THREAD

**Issue by egpbos** [proycon/LaMachine#125]
I'm trying to install PICCL on the LaMachine Docker image. If I understand correctly, this should be done with

```sh
lamachine-add piccl
lamachine-update
```

However, `lamachine-update` seems to do way too much work, taking at least half an hour now. How to speed this up?

**Comment by egpbos** [comment]
Also, if a TASK hangs, e.g. a git clone that hangs due to lost connection, I would expect that I wouldn't have to restart the entire procedure over again, is there any way to do this?

**Comment by proycon** [comment]
It's indeed normal that it takes a while, lamachine-update by definition updates everything (LaMachine doesn't implement the notion of upgrading a single thing as upgrading one thing and not another might break things).

> Also, if a TASK hangs, e.g. a git clone that hangs due to lost connection, I would expect that I wouldn't have to restart the entire procedure over again, is there any way to do this?

No, you can only run the whole thing.. But, if a package is already upgraded it will be much quicker the second time around because the upgrade procedure will detect it's already there (for 90% of the software) and do less.

**Comment by egpbos** [comment]
I just now see that you also uploaded a piccl Docker image, nice! Do you plan on updating this soon? Or do you have a Dockerfile for doing this?

**Comment by proycon** [comment]
Ah yes, but that one is indeed a bit outdated as it's not regularly updated, so you'd still need to do a ``lamachine-update``. I can upload a new one of the current state.

> Or do you have a Dockerfile for doing this?

The LaMachine bootstrap procedure builds both the Dockerfile and container for you.

**Comment by egpbos** [comment]
An updated piccl version would be highly appreciated!

**Comment by proycon** [comment]
I just pushed a new LaMachine PICCL image to Docker Hub

**Comment by egpbos** [comment]
Excellent, will try it out now (for use in #126).

**Comment by egpbos** [comment]
It works nicely! If I could make just one more feature request: when running `ticcl.nf` from this image, it downloads a bunch of Nextflow dependencies. It would be nice if this could already be in the LaMachine PICCL image. One way to accomplish this would be to simply run `ticcl.nf` once when building the Docker image, i.e. from the Dockerfile.

**Comment by proycon** [comment]
Hmm, good point, that should actually have been the case already as Nextflow is explicitly installed in LaMachine. I'll have to investigate why it downloads more stuff.

**Comment by egpbos** [comment]
So it turns out that when I now build this Dockerfile:

```docker
FROM proycon/lamachine:piccl

RUN cd $HOME; touch empty; ticcl.nf --inputdir . --charconfus empty --lexicon empty --alphabet empty

CMD /bin/bash
```
It runs fine and doesn't try to download anything. When I leave out `cd $HOME` I don't have proper permissions, giving the error I also reported [here](https://github.com/proycon/LaMachine/issues/126#issue-384825083).

Could it be that my issue is caused by the fact that I run as a different user? I.e. CWL automatically sets a user uid/gid matching my own (I guess to make sure I have permissions on the files and folders that it also loads). If I try running as root (`USER root`) or with `sudo ticcl.nf`, it also starts downloading.

**Comment by proycon** [comment]
The default user inside the docker container should be lamachine , but a cd $HOME is a good idea as you might indeed land in the root dir where you can't write. I guess I should even do that in LaMachine itself.

**Comment by egpbos** [comment]
It's really odd, even when I stop CWL from overriding the user (with option `--no-match-user`) and I make it set the working directory to `/home/lamachine`, it again starts downloading Nextflow deps. I would expect this to be equivalent to resp. logging in as `lamachine` and doing `cd $HOME`...

**Comment by proycon** [comment]
I don't really know much about CWL and don't know what engine you use for it so I can't really say what's going on there. I'll do a new release with the above commit soon which might sort it.

**Comment by proycon** [comment]
(also, you might want to do a bash -l instead of pure bash in your final CMD)

**Comment by proycon** [comment]
LaMachine v2.4.7 is released and pushed to docker hub (the PICCL image as well)
