### ISSUE TITLE
PICCL Nextflow script not working

### ISSUE THREAD

**Issue by egpbos** [proycon/LaMachine#126]
I installed PICCL and Nextflow on the LaMachine Docker image like so:

```sh
lamachine-add piccl
lamachine-add nextflow
lamachine-update
```

However, when I then try to run `ticcl.nf` I get the following error:

```sh
ERROR ~ .nextflow/history.lock (No such file or directory)

 -- Check '.nextflow.log' file for details
```

Any idea what I can do about this?

I uploaded the Docker image (based on `proycon/lamachine`) to Dockerhub, so you could check that one out, it's at `egpbos/lamachine:piccl`:

```sh
docker run -p 8080:80 -t -i -v $PWD:/data egpbos/lamachine:piccl
```

**Comment by egpbos** [comment]
Unsurprisingly, it seems to help to add the mandatory arguments :) However, now I run into the following problem:

```sh
[ ... many CAPSULE downloads ... ]

CAPSULE: Downloading dependency commons-codec:commons-codec:jar:1.10
Exception while running job
Traceback (most recent call last):
  File "/Users/pbos/sw/miniconda3/envs/ticclat_sprint/lib/python3.7/site-packages/cwltool/job.py", line 323, in _execute
    outputs = self.collect_outputs(self.outdir)
  File "/Users/pbos/sw/miniconda3/envs/ticclat_sprint/lib/python3.7/site-packages/cwltool/command_line_tool.py", line 591, in collect_output_ports
    ret = json.load(f)
  File "/Users/pbos/sw/miniconda3/envs/ticclat_sprint/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/pbos/sw/miniconda3/envs/ticclat_sprint/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/pbos/sw/miniconda3/envs/ticclat_sprint/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/pbos/sw/miniconda3/envs/ticclat_sprint/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[job ticcl_nf.cwl] completed permanentFail
{}
Final process status is permanentFail
```

I retried, but it failed again on the same point, so it seems like it's not just a connection error. What to do?

**Comment by proycon** [comment]
That Python traceback is from your own CWL wrapper it seems? That's not part of PICCL nor LaMachine so I can't say much about it.

**Comment by proycon** [comment]
By the way, I see a reference to miniconda3, I don't recommend combining LaMachine and Anaconda as they both provide a Python installation and mixing things leads to problems or at least, confusion.

**Comment by egpbos** [comment]
Oh sorry, this was also my first time using CWL, so indeed it could very well come from there. Indeed, I was not paying attention, since clearly this was not anything inside the Docker image, the only thing I added to your lamachine image was the PICCL and Nextflow installations (see [Dockerfile](https://github.com/TICCLAT/evaluation_pipeline/tree/master/lamachine_ticcl_docker)), so no Conda inside the Docker.

**Comment by egpbos** [comment]
My problem is apparently somewhere in my input files.
