### ISSUE TITLE
jupyter lab does not start

### ISSUE THREAD

**Issue by kjvoogd** [proycon/LaMachine#129]
hi,

running LaMachine v2.4.7 in a pre-build docker container on osx.

the container works like a charm. one problem i'm having is that the jupyterlab lab does not start. Webserver log states:

`2018/12/23 08:33:27 [error] 138#138: *127 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: latest, request: "GET /lab HTTP/1.1", upstream: "http://127.0.0.1:9888/lab", host: "localhost:8080
", referrer: "http://localhost:8080/"`

The jupyterlab.log states:
`File "/usr/local/lib/python-current/dist-packages/tornado/netutil.py", line 168, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address`
  
All the other stuff runs just fine. Some-thing obvious I'm missing ? Any pointers to get this to work ? 

thanks !

**Comment by kjvoogd** [comment]
I've changed /usr/local/etc/jupyter_notebook_config.py to include:
c.NotebookApp.ip = '0.0.0.0' # listen on all IPs

probably not such a good idea but I'm running docker so I don't really care.

**Comment by proycon** [comment]
Thanks, listening on all interfaces sounds acceptable enough since it's password protected anyway. I adapted the configuration.
