### ISSUE TITLE
oersetter interface?

### ISSUE THREAD

**Issue by eduarddrenth** [proycon/LaMachine#133]
Hi, have the oersetter service running, found the "project" interface and played with it.

Now I want to end up with a url that I can post to: lang=fy|nl, txt=.... or something like it.

I cannot discover how to get there via the project/inputfile/parameter/output visualization setup.

Can you point me to some documentation or maybe explain the mechanism?

**Comment by proycon** [comment]
See the ``/info`` page (http://127.0.0.1:8080/oersetter/info/), it outputs the full RESTful API specific to the webservice. Generic details are also available in the [CLAM Documentation](https://clam.readthedocs.io/en/latest/restapi.html).

**Comment by eduarddrenth** [comment]
Thanks, I'll have a look...

**Comment by eduarddrenth** [comment]
If I understand correctly the flow for one single transaltion is:

- create project (unique name)
- upload file (or text, or url)
- execute project
- poll the status
- retrieve the output (how do I know outputfilename?)
- delete the project

I'll try and play with it...

Does CLAM have xsd's available?

**Comment by proycon** [comment]
Yes, that's correct. 

> Does CLAM have xsd's available?

There's a  RelaxNG schema: https://github.com/proycon/clam/blob/master/docs/clam.rng

**Comment by eduarddrenth** [comment]
Thanks, first tests successful
