### ISSUE TITLE
Frog: "is not a valid NCName" error

### ISSUE THREAD

**Issue by walterdaelemans** [proycon/LaMachine#135]
Some files are not processed by the Frog service: frog-:XML error: <filename> is not a valid NCName. Given that (non-xml) text files are allowed as input files, why should they be valid NCNames?

**Comment by proycon** [comment]
The webservice derives the ID for the document from the filename, though there are checks sometimes invalid names slip through and are caught at a later stage leading to this error which might seem somewhat cryptic. Do the input filenames start with a number by any chance?

**Comment by walterdaelemans** [comment]
Yes they start with a number (year) by design.

**Comment by proycon** [comment]
Ok, that's the cause then, the service is a bit inflexible in this regard. We should add some better validation. For the time being prepending a letter should do the trick probably.

**Comment by walterdaelemans** [comment]
Ok, thanks!

**Comment by kosloot** [comment]
Added a fix in frog
