### ISSUE TITLE
Installation fails on MacOS with: Error: ticcutils 0.19 is already installed To upgrade to 0.20, run `brew upgrade ticcutils`

### ISSUE THREAD

**Issue by gmjonker** [proycon/LaMachine#136]
Installation of LaMachine on my mac failed at several points. I was able to fix a few of them and run `lamachine-lamachine3-update`. But now it fails with 
```
Error: ticcutils 0.19 is already installed
To upgrade to 0.20, run `brew upgrade ticcutils`
```
and the same message for libfolia, ucto, timbl, mbt.

Executing `brew upgrade ticcutils` gives
```
lamachine3 ❯ brew upgrade ticcutils
Error: fbkarsdorp/lamachine/ticcutils 0.20 already installed
```

I don't know how to proceed.

Log:
[lamachine-lamachine3-20190228_100655.log](https://github.com/proycon/LaMachine/files/2914287/lamachine-lamachine3-20190228_100655.log)

**Comment by gmjonker** [comment]
I worked around this problem by changing `brew install {{item}}` to `brew reinstall {{item}}` in `src/LaMachine/roles/languagemachines-basic/tasks/main.yml`.

But then ran into yet another error, during building of `python-frog`. See attached log.

The installation on Mac seems pretty broken!

[lamachine-lamachine3-20190228_134633.log](https://github.com/proycon/LaMachine/files/2915110/lamachine-lamachine3-20190228_134633.log)

**Comment by gmjonker** [comment]
```
[...]
In file included from frog_wrapper.cpp:552:
In file included from /usr/local/include/frog/FrogAPI.h:36:
In file included from /usr/local/include/timbl/TimblAPI.h:35:
In file included from /usr/local/include/timbl/Common.h:32:
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:315:9: error: no member named 'isfinite' in the global namespace; did
      you mean 'finite'?
[...]```
Perhaps `frog-python` expects a different version of `CommandLineTools`?

**Comment by proycon** [comment]
Hmm, it should have been a smoother experiment. It's rather strange that the homebrew upgrade didn't work (after it suggested it itself) and that you needed to force use a ``reinstall`` there. I don't know why that happened, but perhaps I should make ``reinstall`` the default if one runs the update with ``force=1`` to remedy this...

**Comment by proycon** [comment]
@fbkarsdorp Does this homebrew behaviour make any sense to you by any chance?

**Comment by fbkarsdorp** [comment]
Installation failures can be mysterious sometimes. When upgrading, I tend to remove all lamachine related packages with `brew uninstall` and then install them again.

**Comment by proycon** [comment]
Ok, that's not the quickest upgrade path (ideally I don't want to unnecessarily uninstall and reinstall stuff) but perhaps it's necessary at times. I'll implement stricter homebrew behaviour if ``force=1`` is set.

**Comment by proycon** [comment]
Hmm, in fact I now see I already did that in LaMachine (reinstall for force=1)...

**Comment by proycon** [comment]
Thus far I can't reproduce this on our own tests.
