### ISSUE TITLE
X11 display in VM version of lamachine

### ISSUE THREAD

**Issue by Irishx** [proycon/LaMachine#137]
The DISPLAY variable is empty in the VM version of lamachine (that i started with lamachine-Lamachine-activate).

Attempts to set this variable did not work?

Can i use ssh -X from a fresh terminal to the VM to get a version with X forwarding?

**Comment by proycon** [comment]
It's normal that this variable is initially empty, as there is no display and LaMachine does not provide an X server (although it's easy for users to install one if they want). But indeed ssh -X or -Y should do the job.
