### ISSUE TITLE
Integrate oral history ASR in LaMachine

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#140]
Oral history is not fully integrated into LaMachine yet, this depends on #106 first. Then the oral history resources must be made properly downloadable so LaMachine can fetch it. There can't be any absolute paths in the resources!

(relevant for @schemreier ,  @henkvdheuvel, @vanlummelhuizen )

**Comment by HenkvdHeuvel** [comment]
Klinkt goed!
Henk

Op di 14 jan. 2020 13:40 schreef Maarten van Gompel <
notifications@github.com>:
