### ISSUE TITLE
Not able to (re-)install virtualenv during installation LaMachine

### ISSUE THREAD

**Issue by DaanRaven** [proycon/LaMachine#142]
I am trying to install LaMachine because I want to make use of the Frog NLP tool. I have tried to install the stable version in a local user environment. I have not changed any of the settings. However, I keep getting the same error. 

TASK [lamachine-core : (Re)install virtualenv] *********************************
fatal: [testfrogyeah]: FAILED! => {
    "changed": false, 
    "cmd": "pip3 install virtualenv", 
    "rc": 2
}

MSG:

[Errno 2] No such file or directory

I do not know how I can solve this problem.. is there someone who can point me in the right direction?

[lamachine-testfrogyeah.log](https://github.com/proycon/LaMachine/files/3144360/lamachine-testfrogyeah.log)

**Comment by proycon** [comment]
I wonder what goes wrong, this problem doesn't replicate on our test build. Can you try a manual: 

```
sudo pip3 install virtualenv
```

And see what that says?
