### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by Lotteaveline** [proycon/LaMachine#146]
}

TASK [lamachine-core : Obtaining local nginx webserver from source] **************************************************************************************************************************************************************************
fatal: [lotte-HP-Notebook]: FAILED! => {
    "changed": false
}

MSG:

Failed to find required executable hg in paths: /home/lotte/Alpaca/bin:/home/lotte/anaconda3/bin:/home/lotte/bin:/home/lotte/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

TASK [lamachine-core : Obtaining local nginx webserver from source (2nd attempt, insecure fallback)] *****************************************************************************************************************************************
fatal: [lotte-HP-Notebook]: FAILED! => {
    "changed": true,
    "cmd": "hg clone --insecure https://hg.nginx.org/nginx",
    "delta": "0:00:00.001440",
    "end": "2019-06-09 09:56:30.930330",
    "rc": 127,
    "start": "2019-06-09 09:56:30.928890"
}

STDERR:

/bin/sh: 1: hg: not found

MSG:

non-zero return code

**Comment by proycon** [comment]
On what type of linux distribution is this? It seems LaMachine forgot to install hg (mercurial)

**Comment by Lotteaveline** [comment]
I am using the mint distribution of linux


Op zo 9 jun. 2019 om 10:09 schreef Maarten van Gompel <
notifications@github.com>:

**Comment by proycon** [comment]
Hmm, strange, it should have been installed then. You supplied your sudo password at the beginning of the the installation and are not attempting to install without, right?

To circumvent the problem, you can install hg manually as follows: ``sudo apt install mercurial``, and then just try the LaMachine installation or (update) again.

**Comment by Lotteaveline** [comment]
I checked if it was installed and it apparently was not installed so I got
it now! Thanks for helping me!



Op zo 9 jun. 2019 om 10:34 schreef Maarten van Gompel <
notifications@github.com>:
