### ISSUE TITLE
nginx: command not found when starting LaMachine web server

### ISSUE THREAD

**Issue by pboot** [proycon/LaMachine#151]
On a brand new Ubuntu 18.04 system (newly installed, that is, the hardware is from 2016).

Installed curl and python2.

Installed LaMachine using
bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)

Chose options local (1) and stable (1).

Did not change the list of programs to be installed.

Installation finished OK:

PLAY RECAP *********************************************************************
peter-MS-7641              : ok=906  changed=423  unreachable=0    failed=0    skipped=829  rescued=0    ignored=0   
All done, a local LaMachine environment has been built!
- to activate your environment, run: source lamachine-LMPB-activate   (or: ~/bin/lamachine-LMPB-activate)

Ran ~/bin/lamachine-LMPB-activate
Returned a welcome message

However, upon starting the web server:
(LMPB) peter@peter-MS-7641:~$ lamachine-start-webserver
Starting uwsgi...
Starting nginx...
You are using a running the webserver on a privileged port 80, sudo required to start
[sudo] password for peter:
sudo: nginx: command not found
Note: UWSGI emperor log can be found in /home/peter/LMPB/var/log/uwsgi/uwsgi.log
Nginx logs can be found in /home/peter/LMPB/var/log/nginx/
Starting Jupyter Lab...
Note: Jupyter Lab logs can be found in /home/peter/LMPB/var/log/jupyterlab.log

There is no Nginx log in the indicated location.

I attach the install log and the uwsgi log, which shows another error message:
open("./python3_plugin.so"): No such file or directory [core/utils.c line 3724]

[lamachine-LMPB.log](https://github.com/proycon/LaMachine/files/3335340/lamachine-LMPB.log)

[uwsgi.log](https://github.com/proycon/LaMachine/files/3335349/uwsgi.log)

No particular urgency in this, as I'll be using the web services for now.

**Comment by proycon** [comment]
The failure to start nginx was in fact a bug in the activation script, running sudo means losing the virtual environment, so nginx could no longer be find. The above fix addresses it (to be tested and released asap)

**Comment by proycon** [comment]
Should be solved in the new release (2.9.0) now.
