### ISSUE TITLE
Ucto ImportError after update

### ISSUE THREAD

**Issue by roelsmeets** [proycon/LaMachine#154]
I have been using Ucto for quite a while now without any problems. However, after updating lamachine last week I got the following ImportError 
![Schermafbeelding 2019-08-02 om 12 44 25](https://user-images.githubusercontent.com/22320580/62365500-8701c100-b524-11e9-978c-a0222a36c68c.png)

I had one fail during my update, perhaps it has something to do with that
![Schermafbeelding 2019-07-26 om 09 32 50](https://user-images.githubusercontent.com/22320580/62365594-c5977b80-b524-11e9-962d-b14919d03849.png)

I already ran the update force options, but this does not make a difference.

**Comment by proycon** [comment]
Hmm..  It looks as if libicu got updated through homebrew but an older version is still referenced. Do you get a similar error if you just run ``ucto`` on the command line? 

Can you try to explicitly uninstall all our homebrew packages (``homebrew remove ucto frog libfolia ticcutils timbl mbt mbtserver timblserver``)  and then run the LaMachine update with force=2 (that's an even stronger variant that deletes all sources and reobtains and recompiles them).

**Comment by roelsmeets** [comment]
Yes, I get a similar error if I run the command ucto

![Schermafbeelding 2019-08-05 om 13 03 52](https://user-images.githubusercontent.com/22320580/62460460-5a4ae500-b782-11e9-92d2-8a411934f1c7.png)

I tried to uninstall the homebrew packages but it does not recognize the command you propose. 
![Schermafbeelding 2019-08-05 om 13 09 20](https://user-images.githubusercontent.com/22320580/62460513-7d759480-b782-11e9-8c77-dbbe88ea863e.png)

**Comment by proycon** [comment]
I think the command is ``brew remove``

**Comment by roelsmeets** [comment]
Then I get this error

![Schermafbeelding 2019-08-05 om 13 16 20](https://user-images.githubusercontent.com/22320580/62460785-3b008780-b783-11e9-9fc1-7e924b02b747.png)

**Comment by proycon** [comment]
Okay, that's fine, you don't have mbtserver installed, remove it from the list

**Comment by roelsmeets** [comment]
Should I override and force removal?
![Schermafbeelding 2019-08-05 om 13 19 06](https://user-images.githubusercontent.com/22320580/62460924-a185a580-b783-11e9-9858-5a5601fc8f32.png)

**Comment by proycon** [comment]
ah, just add those two to the list as well (and frogdata too probably), and then it should work without forcing.

**Comment by roelsmeets** [comment]
Same error as I got earlier

![Schermafbeelding 2019-08-05 om 13 23 22](https://user-images.githubusercontent.com/22320580/62461119-36889e80-b784-11e9-8fb7-1cd22a8ed370.png)

**Comment by proycon** [comment]
If ucto and friends got successfully removed by homebrew than I'd expect it to give a different error (ucto: command not found). Are you sure the uninstall went correctly?

Of course, to make it install again, you'll need to do the (forced) LaMachine update as mentioned in my original reply.

**Comment by roelsmeets** [comment]
The uninstall did not go correctly, you were right. However, after properly uninstalling 


![Schermafbeelding 2019-08-05 om 13 50 13](https://user-images.githubusercontent.com/22320580/62462537-f88d7980-b787-11e9-870b-94ad14bda7f5.png)

I stil get a fail and a UniCodeDecodeError

![Schermafbeelding 2019-08-05 om 13 49 21](https://user-images.githubusercontent.com/22320580/62462582-0cd17680-b788-11e9-8380-ad0e91ccfe96.png)

**Comment by proycon** [comment]
Hmm.. that one is rather unexpected and should not happen indeed. I'll need to deduce where that happened. What messages were shown above that error?

**Comment by roelsmeets** [comment]
![Schermafbeelding 2019-08-05 om 14 01 08](https://user-images.githubusercontent.com/22320580/62463193-aa797580-b789-11e9-9caf-77f01d706b34.png)
![Schermafbeelding 2019-08-05 om 14 01 21](https://user-images.githubusercontent.com/22320580/62463203-ad746600-b789-11e9-8157-2e8c3608dff5.png)
![Schermafbeelding 2019-08-05 om 14 01 54](https://user-images.githubusercontent.com/22320580/62463206-aea59300-b789-11e9-9cc8-6d538f06325a.png)
![Schermafbeelding 2019-08-05 om 14 02 06](https://user-images.githubusercontent.com/22320580/62463208-b06f5680-b789-11e9-88e5-40e5cd7bf595.png)

**Comment by proycon** [comment]
Hmm, het zou niet nodig moeten zijn maar ik heb een kleine LaMachine fix gecommit (een probeersel). Kan je het nog eens proberen?

Als het dan nog niet werkt, wat krijg je als je ``locale`` invoert? En probeer dan eens ``export LC_ALL=en_US.UTF-8``  om je locale expliciet goed te zetten alvorens de LaMachine update te draaien? Al ook zou dat niet nodig moeten zijn want dat doet lamachine-update ook al automatisch voor je eigenlijk... Het is een beetje een gok nog waarom Ansible (systeem waarop LaMachine gebouwd is) hier nu bij je struikelt.

**Comment by roelsmeets** [comment]
Hi Maarten,

Ik heb nog eens de force=2 update gedaan en krijg dezelfde error.

locale resulteert in dit lijstje:

LANG="nl_NL.UTF-8"
LC_COLLATE="nl_NL.UTF-8"
LC_CTYPE="nl_NL.UTF-8"
LC_MESSAGES="nl_NL.UTF-8"
LC_MONETARY="nl_NL.UTF-8"
LC_NUMERIC="nl_NL.UTF-8"
LC_TIME="nl_NL.UTF-8"
LC_ALL=

Na  export LC_ALL=en_US.UTF-8 en een nieuwe force=2 update krijg ik weer dezelfde error…

Hopelijk kom je er achter waar de kink in de kabel zit! (voor de update had ik dus nergens last van)


PhD Researcher / Lecturer
Literary Studies / Digital Humanities

Radboud Universiteit Nijmegen | Algemene Cultuurwetenschappen | Postbus 9103 | 6500 HD Nijmegen (NL) | Kamer E 11.23 | T. +31 24 36 10 77 | http://www.ru.nl/personen/smeets-r/















Op 5 aug. 2019, om 14:40 heeft Maarten van Gompel <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hmm, het zou niet nodig moeten zijn maar ik heb een kleine LaMachine fix gecommit (een probeersel). Kan je het nog eens proberen?

Als het dan nog niet werkt, wat krijg je als je locale invoert? En probeer dan eens export LC_ALL=en_US.UTF-8 om je locale expliciet goed te zetten alvorens de LaMachine update te draaien? Al ook zou dat niet nodig moeten zijn want dat doet lamachine-update ook al automatisch voor je eigenlijk... Het is een beetje een gok nog waarom Ansible (systeem waarop LaMachine gebouwd is) hier nu bij je struikelt.

**Comment by proycon** [comment]
Heel vreemd, je locale was inderdaad prima... Ik heb nog maar een fix geprobeerd door alle utf-8 uit die file te halen, geen echte oplossing maar meer een snelle patch. Kan je nog eens proberen? (want ik kan het probleem hier überhaupt niet reproduceren)

**Comment by roelsmeets** [comment]
Hm, ik doe opnieuw een update met force=2 en krijg wederom een UnicodeDecodeError… Als ik daarna de mijn code run krijg ik weer een ucto ImportError

Kan ik het je op een of andere manier makkelijker maken om het probleem vast te stellen? (Ucto is vrij essentieel voor mijn huidige project, dus ik hoop dat het niet onoplosbaar is)


PhD Researcher / Lecturer
Literary Studies / Digital Humanities

Radboud Universiteit Nijmegen | Algemene Cultuurwetenschappen | Postbus 9103 | 6500 HD Nijmegen (NL) | Kamer E 11.23 | T. +31 24 36 10 77 | http://www.ru.nl/personen/smeets-r/



[cid:68F9D132-07BB-4FD5-9922-377BC1A75C6A]











Op 5 aug. 2019, om 15:55 heeft Maarten van Gompel <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Heel vreemd, je locale was inderdaad prima... Ik heb nog maar een fix geprobeerd door alle utf-8 uit die file te halen, geen echte oplossing maar meer een snelle patch. Kan je nog eens proberen? (want ik kan het probleem hier überhaupt niet reproduceren)

**Comment by proycon** [comment]
Is de decodeerror weer op precies dezelfde plek? (dat zou vreemd zijn namelijk na de laatste patch)

Het blijft sowieso een mysterie waarom jij tegen dit probleem aanloopt en het elders gewoon goed gaat.

Je zou ook helemaal opnieuw kunnen beginnen, je huidige LaMachine instalatie weggooien (``rm -Rf /users/roelsmeets/LaMachineLaMachine /users/roelsmeets/lamachine-controller``; let op ik ga er hierbij van uit dat je geen andere data in deze LaMachine dirs hebt staan!) en opnieuw bootstrappen (``bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)
``) om te kijken of je dan ook nog tegen het decodeerror probleem aanoopt

**Comment by roelsmeets** [comment]
Ja, de decodeerror is weer op precies dezelfde plek 
![Schermafbeelding 2019-08-06 om 14 28 50](https://user-images.githubusercontent.com/22320580/62539967-c434be80-b856-11e9-8444-d72bb076b355.png)

Ik de LaMachine installatie weggooien en opnieuw bootstrappen.

**Comment by roelsmeets** [comment]
Is dit de bedoeling?
![Schermafbeelding 2019-08-06 om 14 36 33](https://user-images.githubusercontent.com/22320580/62540322-a451ca80-b857-11e9-97d3-3caebde0ff9a.png)

**Comment by proycon** [comment]
er ontbreken wat rechten blijkbaar, gewoon even sudo ervoor zetten

**Comment by roelsmeets** [comment]
Na bootstrappen krijg ik deze error

![Schermafbeelding 2019-08-07 om 12 33 38](https://user-images.githubusercontent.com/22320580/62616373-9f505200-b90f-11e9-91e9-4c113c68950c.png)

**Comment by proycon** [comment]
Ok, die heb ik nu weggehaald want werkt blijkbaar niet met wat oudere ansible versies. Probeer nog eens?

**Comment by proycon** [comment]
(Overigens: Als je op de chat komt kunnen we het misschien wat sneller oplossen aangezien we nu al een tijdje bezig zijn zo..)

**Comment by roelsmeets** [comment]
![Schermafbeelding 2019-08-07 om 13 27 43](https://user-images.githubusercontent.com/22320580/62619544-50a6b600-b917-11e9-91d0-97e003445086.png)
![Schermafbeelding 2019-08-07 om 13 28 22](https://user-images.githubusercontent.com/22320580/62619545-51d7e300-b917-11e9-964b-0af3471703f0.png)
![Schermafbeelding 2019-08-07 om 13 27 54](https://user-images.githubusercontent.com/22320580/62619551-53a1a680-b917-11e9-97f9-9a8e6fa795ce.png)

**Comment by roelsmeets** [comment]
![Schermafbeelding 2019-08-07 om 13 41 26](https://user-images.githubusercontent.com/22320580/62620260-2229da80-b919-11e9-896f-fce96bcbbeb2.png)

**Comment by roelsmeets** [comment]
![Schermafbeelding 2019-08-07 om 15 12 26](https://user-images.githubusercontent.com/22320580/62625653-f4975e00-b925-11e9-8bb3-df7d1d6c6d1b.png)
![Schermafbeelding 2019-08-07 om 15 12 39](https://user-images.githubusercontent.com/22320580/62625656-f5c88b00-b925-11e9-8cdf-db45b4f49021.png)
![Schermafbeelding 2019-08-07 om 15 12 53](https://user-images.githubusercontent.com/22320580/62625665-f7924e80-b925-11e9-831d-23747b21c362.png)
