### ISSUE TITLE
Building local lamachine environment fails

### ISSUE THREAD

**Issue by anlinguist** [proycon/LaMachine#158]
I'm trying to use lamachine to test out Gecco, but I can't seem to build it correctly or update lamachine.

I keep getting an import error for

`python3 -c 'import ucto'`

The error is:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/username/lama/lib/python3.7/site-packages/ucto.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/libfolia/lib/libfolia.11.dylib
  Referenced from: /Users/username/lama/lib/python3.7/site-packages/ucto.cpython-37m-darwin.so
  Reason: image not found`

I'm not sure why this is happening. I can activate the environment, but it will never pass importing ucto, and it looks like this is related to libfolia. I saw this issue (https://github.com/proycon/LaMachine/issues/7 ) but it looks like that was previously fixed. Did libfolia get updated again to break this?

**Comment by proycon** [comment]
I have seen such problems occur before indeed. It looks as if python-ucto is compiled against an older libfolia. Is this an update of an existing LaMachine installation? If so, did you try running the update with the ``force=2`` parameter? (``force=1`` might also be enough but ``force=2`` is a bit more aggressive)
