### ISSUE TITLE
libgnutls-dev not in debian for local installation

### ISSUE THREAD

**Issue by rahiel** [proycon/LaMachine#16]
The local installation tries to install `libgnutls-dev`, but it looks like [it has been removed after Debian 8 (Wheezy)](https://packages.debian.org/search?searchon=names&keywords=libgnutls+dev), so apt shows the error `E: Package 'libgnutls-dev' has no installation candidate` , the LaMachine installation gives an error and continues. I've manually installed all the packages except the gnutls one and the LaMachine installation succeeded (except gecco and [python] timble, but that's because I used python2).

**Comment by proycon** [comment]
Thanks for the report! I have now adapted the global installation to install ``libgnutls28-dev`` instead.
