### ISSUE TITLE
Installing on MacOS (local environment)

### ISSUE THREAD

**Issue by JuneDay** [proycon/LaMachine#160]
[lamachine-TextMining.log](https://github.com/proycon/LaMachine/files/3835366/lamachine-TextMining.log)
 I habe problems with the python versions - on my Mac is a newer version than of LaMachine and therefore the building of a local LaMachine environment failed. I can activate ist, but I cannot start the webserver or do updates.

**Comment by proycon** [comment]
Hmm.. can you try to activate the environment and then run ``lamachine-update nopythoncheck=1``? It will skip the check then and build on the Python 3.6 it used to create the environment. I'm not sure why your global python 3 is different than the one it used to create the environment with.
