### ISSUE TITLE
Bootstrap to build a local LaMachine environment fails while setting LaMachine update script

### ISSUE THREAD

**Issue by ebritoc** [proycon/LaMachine#162]
I'm trying to install LaMachine as a local environment in a Linux server (Ubuntu 18.04) with all the default options (stable version, suggested paths, no change in configuration options, with sudo rights). Unfortunately, retrying the bootstrap has no different outcome and it is not possible to activate the environment via "lamachine-lama1-activate" either:

<pre>TASK [lamachine-core : Set LaMachine update script] ************************************************************
<font color="#CC0000">fatal: [***]: FAILED! =&gt; {</font>
<font color="#CC0000">    &quot;changed&quot;: false, </font>
<font color="#CC0000">    &quot;checksum&quot;: &quot;00357ca32d86edcd235632bf48bea28b57550f88&quot;</font>
<font color="#CC0000">}</font>

<font color="#CC0000">MSG:</font>

<font color="#CC0000">Unsupported parameters for (copy) module: output_encoding Supported parameters include: attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, original_basename, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate</font>

PLAY RECAP *****************************************************************************************************
<font color="#CC0000">***</font> : <font color="#4E9A06">ok=5   </font> changed=0    unreachable=0    <font color="#CC0000">failed=1   </font>

======================================================================================
<font color="#EF2929"><b>Building a local LaMachine environment has failed unfortunately.</b></font> You have several options:
 - Retry the bootstrap, possibly tweaking configuration options
 - Attempt to activate the environment (run: lamachine-lama1-activate) and debug the problem
 - Run lamachine-lama1-update after activating the environment to see if the problem corrects itself
</pre>

[lamachine-lama1.log](https://github.com/proycon/LaMachine/files/3887340/lamachine-lama1.log)

**Comment by proycon** [comment]
Though this didn't occur in our own tests, I have just now made an adjustment that should hopefully solve it. Could you try again? Might be related to different ansible versions.

**Comment by ebritoc** [comment]
It worked. Thanks!
