### ISSUE TITLE
VM version installation on MacOs 

### ISSUE THREAD

**Issue by pdakwal** [proycon/LaMachine#163]
Hi
I am trying to install the Virtual Machine version of the LaMachine on MacOs (Sierra), I am getting following error:

Path: <provider config: virtualbox>
Line number: 69
Message: NoMethodError: undefined method `>' for nil:NilClass

Not sure what could be possibly be wrong. Please help

**Comment by proycon** [comment]
You are using the bootstrap method I presume (``bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)``). Could you provide a bit more context? What was last reported before things went wrong? Did the installation produce a log file (will be mentioned at the end if so)? If there is a log file, can you attach it?

**Comment by pdakwal** [comment]
Yes. Using the bootstrap method. The log file just says this:

Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: virtualbox>
Line number: 69
Message: NoMethodError: undefined method `>' for nil:NilClass

**Comment by proycon** [comment]
It looks as if the ``extra_disksize`` parameter in the configuration did not get any value for some reason I don't understand yet (unless you accidentally edited it). I could not reproduce the problem locally. When you execute the bootstrap, it presents an overview of the configuration options, in there you should find ``extra_disksize: 0`` (or another number). 

Could you delete your ``lamachine-controller`` directory (in the dir where you ran the bootstrap) and try again? I have also updated LaMachine to a new version in the meantime.

**Comment by pdakwal** [comment]
@proycon followed as you suggested. Getting a new error:

Bringing machine 'palama4' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.

**Comment by proycon** [comment]
Sorry for the delay, if this issue is still unresolved, can you try: ``vagrant plugin install vagrant-vbguest`` ? It seems those are missing, even though they should have been automatically installed by the bootstrap procedure.
