### ISSUE TITLE
vagrant : command not found

### ISSUE THREAD

**Issue by bnrabander** [proycon/LaMachine#166]
after installing LaMachine:
/Users/Kees/bin/lamachine-lamachine-start: line 3: vagrant: command not found

**Comment by proycon** [comment]
Everything in the installation went well? That would have also used vagrant after all, so I'm a bit surprised if that stage completed without problem and you get this error now. 

It looks like you're on macOS? ``vagrant`` seems not to be in your ``$PATH`` for some reason, perhaps you can locate it on your system?
