### ISSUE TITLE
Error adding Alpino to pre-built Docker image on WSL 1  / "own build" routine on WSL

### ISSUE THREAD

**Issue by gnmarten** [proycon/LaMachine#167]
I'm trying to add Alpino to the pre-built docker image, running Docker within the Windows Subsystem for Linux (WSL 1), Windows 10

Linux version: Ubuntu 18.04. 

command lamachine-add Alpino; lamachine-update --> is this the right way to do this?

I'm under the impression that the lamachine-update fails at the very last step, namely when installing Alpino 

"The LaMachine update failed!"    : ok=1011 changed=389  unreachable=0    failed=1    skipped=884  rescued=0    ignored=3"

In a second attempt, I added the Alpino dependencies via apt, prior to running the update.

I'm afraid I don't understand how to restrict the update process to --only=alpino, since it takes quite some time to run the whole update process. 

This is the error-message

TASK [alpino : Installing global dependencies for Alpino (Debian/Ubuntu)] ******
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: "{{item}}"`, please use `name: ['libtcl8.6', 'libtk8.6',
'libwww-perl', 'libxslt1.1', 'tk', 'unzip']` and remove the loop. This feature
will be removed in version 2.11. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
failed: [localhost] (item=[u'libtcl8.6', u'libtk8.6', u'libwww-perl', u'libxslt1.1', u'tk', u'unzip']) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": [
        "libtcl8.6",
        "libtk8.6",
        "libwww-perl",
        "libxslt1.1",
        "tk",
        "unzip"
    ]
}

MSG:

value of state must be one of: absent, build-dep, fixed, latest, present, got: installed

RUNNING HANDLER [lamachine-core : lamachine-build-registry] ********************

Thanks for this brilliant environment BTW. If I might suggest a change to the Readme: it took me quite some time to find out that it is not possible to run run Alpino within LaMachine on Windows itself and that other restrictions apply depending on one's OS.

**Comment by gnmarten** [comment]
I ran into the exact same error while performing the "own build" routine on Linux Ubuntu 16.04: Alpino is the sole error.

**Comment by tjeerdhans** [comment]
Had the same error, found this: [what does state=installed mean in ansible apt? (stackoverflow)](https://stackoverflow.com/a/39903113/160608).

Apparently, the installed version of ansible doesn't accept the deprecated alias anymore.

I tried changing 'installed' to 'present' in `/lamachine/roles/alpino/tasks/main.yml`, but lamachine-update doesn't seem to pick that up. Should I change it somewhere else?

> I'm afraid I don't understand how to restrict the update process to --only=alpino, since it takes quite some time to run the whole update process.

`--only alpino` seems to work for me (without  '=')

**Comment by proycon** [comment]
Sorry for the delay! Took a while before I could look into this,   @tjeerdhans: thanks for the proposed solution.

I have now updated LaMachine not to use the deprecated solution anymore. If you do lamachine-update it should work (I'll publish new docker/VM images tomorrow),

> --only alpino seems to work for me (without '=')

Correct, it should be without ``=``

`lamachine-add Alpino; lamachine-update --> is this the right way to do this?`

Yes, that should work, since you use docker, make sure to commit the changes to a new image afterwards.

**Comment by tjeerdhans** [comment]
Great, thanks!

In the mean time, I changed 'installed' into 'present' in `/usr/local/src/LaMachine/roles/alpino/tasks/main.yml`, then it worked. Was going to submit a PR, but had to leave for dinner :-)

Should it have been picked up in `/lamachine/roles/alpino/tasks/main.yml`?

**Comment by proycon** [comment]
> Should it have been picked up in /lamachine/roles/alpino/tasks/main.yml?

No, if you're in a VM/container that's usually not really used much anymore after the initial installation. You can make changes in ``$LM_SOURCEPATH/LaMachine``, as you noticed. Though the update script actively updates itself from the remote each time, so in worst case you might run into git merge conflicts blocking the update.

**Comment by proycon** [comment]
Should be solved now in the latest LaMachine (please reopen if problems persist)
