### ISSUE TITLE
latest lamachine-* scripts give "docker: invalid reference format."

### ISSUE THREAD

**Issue by decentral1se** [proycon/LaMachine#170]
I used the bash one line incantation and installed the Docker lamachine.

```
➜  docker run -t -p 8080:80 -h --mount type=bind,source=/home/decentral1se/work/lamachine,target=/data proycon/lamachine:lamachine lamachine-start-webserver -f
```

> docker: invalid reference format.
> See 'docker run --help'.

I'm on `Docker version 17.05.0-ce, build 89658b` on Debian Stretch.

I'm also on a Zsh shell.

**Comment by decentral1se** [comment]
Uhhhhh the `-h` shouldn't be there?

**Comment by decentral1se** [comment]
OK, the README commands work fine though :sun_with_face: 

> docker pull proycon/lamachine
> docker run  -p 8080:80 -h latest -t -i proycon/lamachine

**Comment by proycon** [comment]
The ``-h`` is there to pass a hostname, it takes one argument (which is missing in your initial call). I also see end-of-line slashes in your one-line invocation, shouldn't those be backslashes (line continuation character)?

**Comment by decentral1se** [comment]
Ah, I see. I put (incorrectly) the backslashes for formatting but didn't actually include them when running the command. I removed them now. I'm a bit unsure what this error is put for now, I'm not affected (since https://github.com/proycon/LaMachine/issues/170#issuecomment-595702542).
