### ISSUE TITLE
How to use laMachine local installation in python with PyCharm ?

### ISSUE THREAD

**Issue by Skylixia** [proycon/LaMachine#177]
I have installed laMachine locally on a Ubuntu 18 system.
I would like to use the python-frog library that is included in laMachine
I used the import as indicated in the frog documentation but this is not recognized:
from frog import Frog, FrogOptions

how to make use of the libraries installed with laMachine so Python recognize them ?

**Comment by proycon** [comment]
Are you sure are running Python from within the LaMachine environment? You need to activate your environment with ``lamachine-activate`` every time yuo want to work with it. Subsequently, if you run a Python interpreter it should recognize the frog import.

**Comment by Skylixia** [comment]
I do run the environment with lamachine-activate and get the expected response from the command line that LaMachine is running. From the command line tuned in LaMachine, I can run the script no problem indeed. However, I'd like to be able to code with an IDE (PyCharm) because this is more convenient. In that case, the module is not recognized and the IDE doesn't see LaMachine installation as a virtual environment to be able to configure with it.
Any suggestion on how to be able to have the LaMachine installation recognized by the python interpreter without having to run python3 script.py in the command line each time ?
Thank you !

**Comment by proycon** [comment]
Ok, I see what you mean. You'll have to tell PyCharm to use the Python interpreter from LaMachine. You can find generic instructions on how to do that here: https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html , select "existing environment" and point the interpreter to ``/path/to/your/lamachine/bin/python`` (if you're unsure where exactly that is, within the shell after LaMachine activation, type ``echo "$LM_PREFIX/bin/python"`` to get the full path).

I don't use PyCharm myself, but perhaps this bypasses the actual activation script. If you encounter errors loading the frog module you may need to configure some extra environment variables in PyCharm: ``LD_LIBRARY_PATH=/path/to/your/lamachine/lib``

**Comment by Skylixia** [comment]
Thank you for the help ! It was indeed needed to manually add LD_LIBRARY_PATH=/path/to/your/lamachine/lib. Now it works 👍
