### ISSUE TITLE
Alpino 404

### ISSUE THREAD

**Issue by gnmarten** [proycon/LaMachine#191]
--2021-01-03 10:00:50--  http://www.let.rug.nl/vannoord/alp/Alpino/versions/binary/latest.tar.gz
Resolving www.let.rug.nl (www.let.rug.nl)... 129.125.2.210
Connecting to www.let.rug.nl (www.let.rug.nl)|129.125.2.210|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-01-03 10:00:50 ERROR 404: Not Found.

**Comment by kosloot** [comment]
Well, it seems the whole let.rug.nl domain is gone, for now?
Not a thing we in Nijmegen can fix. @proycon  any alternative locations available?

**Comment by gnmarten** [comment]
seems to be up again, but now I ran into
Failed to retrieve the maven metadata file: /edu/stanford/nlp/stanford-corenlp/maven-metadata.xml because of HTTP Error 501: HTTPS Requiredfor URL http://repo1.maven.org/maven2/edu/stanford/nlp/stanford-corenlp/maven-metadata.xml

501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required

**Comment by proycon** [comment]
Here too, something seems to have changed at the remote server end, but this we can fix. If you try again it should now work.
