### ISSUE TITLE
Installation issue with python3-apt in virtualenv and possible solution

### ISSUE THREAD

**Issue by bma-vandijk** [proycon/LaMachine#192]
Hi,

I recently installed the localenv flavour and am using Ubuntu 2020.182. It was the default installation without adding any additional packages. However, when I tried to add other software I quickly ran into this error on a Python dependency that seemed to be missing in the virtual environment. 

> TASK [lamachine-core : Installing aptitude (APT)] ******************************
[1;35m[WARNING]: Updating cache and auto-installing missing dependency: python3-apt[0m
[0;31mfatal: [LAPTOP-5N7G0RHD.localdomain]: FAILED! => {[0m
[0;31m    "changed": false[0m
[0;31m}[0m
[0;31m[0m
[0;31mMSG:[0m
[0;31m[0m
[0;31mCould not import python modules: apt, apt_pkg. Please install python3-apt package.[0m

I think I solved this problem for now with the solution at the bottom of this page https://github.com/ansible/ansible/issues/14468 and I installed `python3-apt` in the `site-packages` folder in the virtual environment manually. I was able to update LaMachine and install the Alpino package afterwards without problems.

I just wanted to let you and other users know how to potentially solve this issue. I love the LaMachine distribution so far by the way, thank you for putting all of this together!

the log file:
[lamachine-lama-20210107_091225.log](https://github.com/proycon/LaMachine/files/5786327/lamachine-lama-20210107_091225.log)

**Comment by proycon** [comment]
Thanks for the report! I hadn't seen this problem pop up before but I can indeed reproduce it now.  I wonder if the latest ansible version triggered this. I'm working on a fix.
