### ISSUE TITLE
lamachine-update failed to install kaldi / kaldi nl on ponyland

### ISSUE THREAD

**Issue by martijnbentum** [proycon/LaMachine#195]
Hi Maarten

I tried to add Kaldi and Kaldi nl to my lamachine installation, but this failed:
lamachine-add kaldi kaldi_nl
lamachine-update

I attached the log file
[lamachine-LM_kaldi-20210420_152747.log](https://github.com/proycon/LaMachine/files/6344086/lamachine-LM_kaldi-20210420_152747.log)

Best,
Martijn

**Comment by proycon** [comment]
I think this may have something to do with there not being a GPU in the machine you're compiling on.. I'm running a test on anothe ponyland server now..

**Comment by martijnbentum** [comment]
I thought so as well, but I also ran it on rarity.

**Comment by proycon** [comment]
When compiling on ponyland, you may also want to set "kaldi_test_ignore_errors: true" in the LaMachine configuration, when I set that the compilation succeeded on mlp09. 

I also noticed that on some ponies the symlink to  /usr/local/cuda was broken so that may also play a role. I reported this to the sysadmins.

**Comment by martijnbentum** [comment]
Ah interesting, because mlp09 does not have any gpu nor the latest cuda driver 11 instead of 11.2
If I set ignore errors will cuda still work?

**Comment by proycon** [comment]
Ah you're right, it doesn't even have a GPU! I was mistaken. But indeed compilation succeeded there with  "kaldi_test_ignore_errors: true". Regardless of GPU, it does need to be able to link against cuda, and it seems we again have have a bit of a scattered situation on the servers regarding cuda versions unfortunately :/

**Comment by martijnbentum** [comment]
Hoi Maarten,

Ik heb wat problemen bij de installatie van lamachine / kaldi. Ik had vorige week nog een paar keer gemaild, omdat het logbestand te groot was voor github. Ik vroeg me af heb je binnenkort tijd om mij te helpen bij de installatie?

Probleem:
-Ik kan kaldi niet installeren in lamachine, ik kreeg een cuda error
-Op blossomforth met ignore kaldi error, zoals je voorstelde, lukte de installatie ook niet
-Ik heb toen geprobeerd lamachine opnieuw te installeren (oorspronkelijke installatie verwijderd), maar dit gaf weer een error: een npm error

De logbestanden heb ik gestuurd in de eerdere mails. Als je meer informatie nodig hebt hoor ik het graag.

Alvast bedankt!

Groet,
Martijn

**Comment by proycon** [comment]
Hoi Martijn, sorry voor de vertraging. Ik ga het nu onderzoeken!

**Comment by martijnbentum** [comment]
Bedankt!

**Comment by proycon** [comment]
Die npm error is wat vreemd (en heeft met iets te maken wat je eigenlijk niet eens nodig hebt, 'labirinto', dat is de portal website in LaMachine zoals je ook op https://webservices.cls.ru.nl ziet). Ik denk inderdaad dat het iets te maken heeft met een oude installatie die in de weg staat, of eventueel zelfs gecachede dingen in ``~/.npm``. 

Had je heel ``/vol/tensusers5/mbentum/lm_martijn/`` verwijderd voor herinstallatie? Wat je ook kan doen is om tijdens de LaMachine installatie in de installatie manifest "labirinto" eruit te halen (het zou niet nodig moeten zijn maar je hebt het toch niet nodig). Mijn suggestie om vers te beginnen:

* Gooi ``/vol/tensusers5/mbentum/lm_martijn/`` weg
* Gooi ``/vol/tensusers5/mbentum/lamachine-controller/`` weg
* Gooi ``~/.npm`` weg (even aangenomen dat je zelf niks met npm doet en je hier geen belangrijke settings bewaard)
* Haal labirinto uit de installatie manifest bij herinstallatie (zou niet nodig moeten zijn maar better safe than sorry)
* Vergeet niet ``kaldi_test_ignore_errors: true`` te zetten in de configuratie, want anders loop je tegen de kaldi test suite aan die soms faalt.


PS: Gefeliciteerd met het behalen van je PhD! :)

**Comment by martijnbentum** [comment]
Bedankt!

Ik ga het proberen.

Groet,
Martijn

**Comment by martijnbentum** [comment]
Hoi Maarten,

Geen errors meer ;-). Bedankt!

Groet,
Martijn
