### ISSUE TITLE
error: required file './ltmain.sh' not found

### ISSUE THREAD

**Issue by PRANEETH-ALURU** [proycon/LaMachine#197]
TASK [lamachine-cpp-automake : ticcutils - Run autoreconf if needed (through bootstrap if it exists)] ******************
fatal: [lamachine-vm]: FAILED! => {
    "changed": true,
    "cmd": "#!/bin/bash\nif [ -f ./bootstrap.sh ]; then\n  bash ./bootstrap.sh\n  exit $?\nelif [ -f ./bootstrap ]; then\n  bash bootstrap\n  exit $?\nelif [ -f ./configure ]; then\n  #we already have a configure, things should be fine\n  exit 0\nelif [ -f ./configure.ac ]; then\n  #no bootstrap, we do it ourselves:\n  autoreconf --install\n  exit $?\nelse\n  echo \"No configure, configure.ac or bootstrap.sh found!\">&2\n  exit 1\nfi\n",
    "delta": "0:01:03.864056",
    "end": "2021-05-16 19:44:06.116363",
    "rc": 1,
    "start": "2021-05-16 19:43:02.252307"
}

STDERR:

aclocal: installing 'm4/ax_check_zlib.m4' from '/usr/share/aclocal/ax_check_zlib.m4'
aclocal: installing 'm4/ax_lib_socket_nsl.m4' from '/usr/share/aclocal/ax_lib_socket_nsl.m4'
aclocal: installing 'm4/ax_type_socklen_t.m4' from '/usr/share/aclocal/ax_type_socklen_t.m4'
aclocal: installing 'm4/libtool.m4' from '/usr/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/share/aclocal/lt~obsolete.m4'
aclocal: installing 'm4/pkg.m4' from '/usr/share/aclocal/pkg.m4'
configure.ac:23: installing './compile'
configure.ac:23: installing './config.guess'
configure.ac:23: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:23: error: required file './ltmain.sh' not found
configure.ac:6: installing './missing'
src/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1

MSG:

non-zero return code

RUNNING HANDLER [lamachine-core : lamachine-build-registry] ************************************************************

PLAY RECAP *************************************************************************************************************
lamachine-vm               : ok=273  changed=136  unreachable=0    failed=1    skipped=492  rescued=0    ignored=0

======================================================================================
Building a local LaMachine environment has failed unfortunately. You have several options:
 
My sys info:
OS Name:	Microsoft Windows 10 Home Single Language
Version:	10.0.19042 
System Model:	Inspiron 15-3000 series

I don't have much experience in using VMs and surfing web. I tried using WSL. 
I'm running the bash command " bash <(curl -s https://raw.githubusercontent.com/proycon/LaMachine/master/bootstrap.sh)" given, on WSL. I'm getting this error above. I've surfed  the web and tried the methods like libtoolize for the errors which I'm getting. I'm still unable to solve this issue. I think there aren't any specific dependencies required, I've installed the dependencies of the manual installation tho. Please help me through this. Please tell me any command changes if required or any other steps.

**Comment by proycon** [comment]
I don't really have a Windows machine to reproduce this on. I wonder why you get this error. Libtoolize should indeed be invoked automatically to create the ltmain.sh symlink, all dependencies should be automatically provided by LaMachine. What Linux distribution are you using with your WSL? We recommend Ubuntu Linux 20.04 .

**Comment by proycon** [comment]
Ok, I found a machine to try this on and I could not reproduce the problem. It has just passed this stage succesfully.

**Comment by PRANEETH-ALURU** [comment]
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
WSL version 1

Thanks for replying.
I think the version might be the problem.  I have to go through it.  

I'm planning to use NLP features of Gecco.  Are the context aware spell check modules pre-trained in it or should we train them manually ?
