### ISSUE TITLE
Error in TASK when installing LaMachine on Ponyland

### ISSUE THREAD

**Issue by VirginiaMeijer** [proycon/LaMachine#200]
Hello,

I tried installing LaMachine on Ponyland following [the wikipage](https://ponyland.science.ru.nl/doku.php?id=wiki:ponyland:webservices&s[]=lamachine). The installation starts but quickly (within the first minute) runs into an error. I have added the log file and the error occurs that occurs:

[lamachine-transformersLM.log](https://github.com/proycon/LaMachine/files/6592551/lamachine-transformersLM.log)

> TASK [lamachine-core : Installing python-apt into virtual environment] *********
> fatal: [mlp01.science.ru.nl]: FAILED! => {
>     "changed": true,
>     "cmd": "#!/bin/sh\nif [ ! -d python3-apt ]; then\n    apt-get download python3-apt || exit 1\n    dpkg -x python3-apt*.deb python3-apt || exit 1\n    cp -r python3-apt/usr/lib/python3/dist-packages/* /vol/tensusers3/vmeijer/transformersLM/lib/python3.5/site-packages/ || exit 1\n    cd /vol/tensusers3/vmeijer/transformersLM/lib/python3.5/site-packages/ || exit 1\n    mv apt_pkg.*.so apt_pkg.so || exit 1\n    mv apt_inst.*.so apt_inst.so || exit 1\nfi\n",
>     "delta": "0:00:00.022025",
>     "end": "2021-06-03 16:38:42.858431",
>     "rc": 1,
>     "start": "2021-06-03 16:38:42.836406"
> }
> 
> STDERR:
> 
> E: Opening /etc/apt/sources.list.d/intelproducts.list - ifstream::ifstream (13: Permission denied)
> E: The list of sources could not be read.
> 
> 
> MSG:
> 
> non-zero return code

I'm not sure what files the error refers so any help is appreciated. Thanks!

**Comment by proycon** [comment]
Ok, I implemented a fix for situation in case this happens.

Moreover, I see you are installing on mlp01/applejack, this is probably NOT what you want. Install on any other pony and you can use your LaMachine installation from all ponies (except applejack), if you install on applejack you can only use it there. I'll update the wiki page to clarify that.

**Comment by VirginiaMeijer** [comment]
Okay, thanks for the clarification about applejack. You are right, that is not what I intended. I tried installing it on mistlane and after that on thunderlane and both times it throws this error directly after starting the installation:

```
Running ansible command from /vol/tensusers3/vmeijer/lamachine-controller/transformersLM/LaMachine: ansible-playbook  -i /vol/tensusers3/vmeijer/lamachine-controller/transformersLM/LaMachine/hosts.ini /vol/tensusers3/vmeijer/lamachine-controller/transformersLM/LaMachine/install.yml -v
Traceback (most recent call last):
  File "/vol/tensusers3/vmeijer/lamachine-controller/transformersLM/bin/ansible-playbook", line 63, in <module>
    import ansible.constants as C
  File "/vol/tensusers3/vmeijer/lamachine-controller/transformersLM/local/lib/python2.7/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/vol/tensusers3/vmeijer/lamachine-controller/transformersLM/local/lib/python2.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/vol/tensusers3/vmeijer/lamachine-controller/transformersLM/local/lib/python2.7/site-packages/jinja2/environment.py", line 7, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

I tried activating the environment with the activate command and it does seem to open a LaMachine install but I get the following error. The environment also cannot be deactivated, only exited.

`/vol/tensusers3/vmeijer/transformersLM/bin/activate: line 98: /vol/tensusers3/vmeijer/transformersLM/bin/activate.d/*.sh: No such file or directory`

Is this a continuation of the previous error or is it something new? I didn't include the log files, because the log files only showed the errors I already copied above.

**Comment by proycon** [comment]
This may still have something to do with the earlier error still, could you completely remove the ``lamachine-controller/`` directory and try installing from scratch?

**Comment by VirginiaMeijer** [comment]
I removed the folders and the installer started from scratch. I thought it was working, because it had been running and installing for about an hour. But, it ran into an error:

> TASK [Installing Labirinto dependencies (2nd attempt)] *************************
> 
> TASK [lamachine-run : Running npm install] *************************************
> fatal: [mlp13.science.ru.nl]: FAILED! => {
>     "changed": false,
>     "cmd": "#!/bin/bash\nexport LM_QUIET=1\nif [ -e /home/vmeijer/bin/lamachine-transformersLM-activate ]; then\n    source /home/vmeijer/bin/lamachine-transformersLM-activate\nelse\n    echo \"Activation script /home/vmeijer/bin/lamachine-transformersLM-activate not found! \">&2\n    exit 2\nfi\nhash -r  #clear cache\necho \"Run environment:\">&2\necho \"    LM_NAME=$LM_NAME\">&2\necho \"    PATH=$PATH\">&2\necho \"    LD_LIBRARY_PATH=$LD_LIBRARY_PATH\">&2\necho \"    VIRTUAL_ENV=$VIRTUAL_ENV\">&2\necho \"    PYTHONPATH=$PYTHONPATH\">&2\necho \"    PYTHON=$(which python3)\">&2\necho \"    PIP=$(which pip3)\">&2\necho \"    LANG=$LANG\">&2\necho \"    LC_ALL=$LC_ALL\">&2\necho \"Running: npm install\">&2\nnpm install\n",
>     "delta": "0:03:25.324008",
>     "end": "2021-06-04 12:59:06.312885",
>     "rc": 1,
>     "start": "2021-06-04 12:55:40.988877"
> }
> 
> STDOUT:
> 
> Now using node v16.3.0 (npm v7.16.0)

I tried activating and updating the virtual environment but ran into the same error as earlier that the activation script couldn't be found. I attached the log file.
[lamachine-transformersLM.log](https://github.com/proycon/LaMachine/files/6598237/lamachine-transformersLM.log)

**Comment by proycon** [comment]
Right, I should have warned you about that one. I ran across it on ponyland as well, though other systems seem fine. Please see #198 for a workaround until we find a more permanent solution.

**Comment by VirginiaMeijer** [comment]
I removed all folders and reran the install without `labirinto` and few cups of coffee later it has worked! Thanks for the help and quick replies
