### ISSUE TITLE
Installation issue with Kaldi

### ISSUE THREAD

**Issue by bma-vandijk** [proycon/LaMachine#201]
Hi,

While attempting to install Kaldi on a fresh LaMa distribution I get the following error:

STDERR:
***configure failed: Could not find file /include/fst/fst.h:
  you may not have installed OpenFst. See ../tools/INSTALL ***

Any pointers on how I can solve this?

Thanks in advance!

[lamachine-lama-20210625_092141.log](https://github.com/proycon/LaMachine/files/6715039/lamachine-lama-20210625_092141.log)

**Comment by proycon** [comment]
Hi, 

LaMachine tries to compile and install openfst for you, but looking at your log, it seems your openfst compilation failed as your machine ran out of memory, see the following excerpt from your log:

```
STDERR:

virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
```

I don't know how much you have available and whether there's some memory left to free?

**Comment by bma-vandijk** [comment]
Thanks for the quick reply!

Good point, I did this on a machine with only 8GB ram, maybe that's a little bit too optimistic, will try it on another machine with 16GB
