### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by bma-vandijk** [proycon/LaMachine#202]
Hi, I encountered another issue while trying to update my LaMachine local flavour. 
Thanks in advance for helping me out :)

--
fatal: [LAPTOP-5N7G0RHD.localdomain]: FAILED! => {}

MSG:

The conditional check 'python3apt.rc == 2' failed. The error was: error while evaluating conditional (python3apt.rc == 2): 'python3apt' is undefined

[lamachine-lama-20210714_154005.log](https://github.com/proycon/LaMachine/files/6816534/lamachine-lama-20210714_154005.log)

**Comment by proycon** [comment]
Thanks, I was preparing a new release as we speak and ironing out any problems. This issue should now be solved.

**Comment by bma-vandijk** [comment]
Thanks for the quick reply, will try it!

**Comment by proycon** [comment]
I think there are still a few other quirks that might pop up, so you might want to wait for a few hours, working on it now.
