### ISSUE TITLE
LaMachine clean install update fails

### ISSUE THREAD

**Issue by lpwevers** [proycon/LaMachine#207]
Hi,

I did a clean install of the LaMachine in docker,, using the Dockerfile provided here:
https://github.com/opensource-spraakherkenning-nl/Kaldi_NL/blob/master/Dockerfile

After starting the container it seems like it automatically starts an update. This fails and terminates the docker container.  The error I'm getting is this:
```
TASK [lamachine-python-install : Installing Python Package: overview :: do_registration] ***
ok: [localhost] => {
    "do_registration": true
}

TASK [lamachine-python-install : codemetapy - Git clone/pull] ******************
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": [
        "/usr/bin/git",
        "fetch",
        "--tags",
        "origin"
    ]
}

MSG:

Failed to download remote objects and refs:  fatal: unable to access 'https://github.com/proycon/codemetapy/': Operation timed out after 300020 milliseconds with 0 out of 0 bytes received


PLAY RECAP *********************************************************************
localhost                  : ok=51   changed=8    unreachable=0    failed=1    skipped=63   rescued=0    ignored=2

```
I verified that the server can access the mentioned https://github.com/proycon/codemetapy/ without any issues by manually running:
git clone https://github.com/proycon/codemetapy/

I've attached the log generated by the update.

[lamachine-core-20211119_133707.log](https://github.com/proycon/LaMachine/files/7570671/lamachine-core-20211119_133707.log)

Kind regards,
Louis

**Comment by proycon** [comment]
The error is indeed pretty clear, the git repo (which does exist as you verified) couldn't be accessed. Either github had a temporary glitch (but then it should probably work when you try again) or there is a problem causing the docker container not being able to access the network (or communicate outside). 

You already verified your network connection, on the host system system I presume, but it is possible that there is something wrong in the docker configuration, or in the docker container itself, or possibly even in the firewall on the host (if there is one).

A way to test would be to build a simple custom container derived from ``ubuntu:focal`` (which is what LaMachine uses too), and then see if you have network connectivity from within that container? Based on whether that fails or succeed we can further pinpoint the issue.

**Comment by proycon** [comment]
Alternatively, you can also try to build the container on another system entirely... It doesn't really matter much where it is built.

**Comment by lpwevers** [comment]
Thanks for the quick reply. Looks like I got it working now. It turns out the "lamachine" user was ignoring the proxy settings in /etc/environment.

I exported the settings on the command line and ran the update again. I now got past the github part.

**Comment by lpwevers** [comment]
And unfortunately it now fails at this step:
```
--2021-11-22 09:49:11--  https://nlspraak.ewi.utwente.nl/open-source-spraakherkenning-NL/Models_Starterpack.tar.gz
Resolving mail.lokaal (mail.lokaal)... *****
Connecting to mail.lokaal (mail.lokaal)|*****|:80... connected.
Proxy tunneling failed: Service UnavailableUnable to establish SSL connection.
Unable to download models from nlspraak.ewi.utwente.nl!

```
But that seems fair enough since nlspraak.ewi.utwente.nl seems to be down. So I'll wait and see if that comes back online.

**Comment by proycon** [comment]
Right, I can reproduce that too. I'll try to contact someone from there to see what's going on.

**Comment by proycon** [comment]
We're still waiting for the upstream party to fix the server or make the file available so we can host is elsewhere, please hold on for a bit...

**Comment by proycon** [comment]
We obtained the models and moved them to a server under our control now, so this issue should now be fixed and  you can rebuild. (make sure to clean the docker build cache)

**Comment by lpwevers** [comment]
Thanks. I've now successfully built the LaMachine docker image.
