### ISSUE TITLE
error during lamachine-python-install : python-ucto on macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by antalvdb** [proycon/LaMachine#212]
[lamachine-stable-20211219_163428.log](https://github.com/proycon/LaMachine/files/7741093/lamachine-stable-20211219_163428.log)

**Comment by kosloot** [comment]
This should have been solved in the latest Ucto release 0.24.1
https://github.com/LanguageMachines/ucto/releases

BUT:
in this log:

Warning: fbkarsdorp/lamachine/ucto 0.23 is already installed and up-to-date.
To reinstall 0.23, run:

So this installs NOT the newest Ucto version.

I wonder if @proycon can fix this or do we need @fbkarsdorp ?

**Comment by proycon** [comment]
Right, I forgot to update the homebrew packages. I've done so now, so I
hope this is now fixed.

**Comment by antalvdb** [comment]
Fixed indeed!
