### ISSUE TITLE
error installing pycrypto on macOS 12.2

### ISSUE THREAD

**Issue by antalvdb** [proycon/LaMachine#213]
[lamachine-stable-20220130_165658.log](https://github.com/proycon/LaMachine/files/7966309/lamachine-stable-20220130_165658.log)

The key error that is reported is:
      src/_fastmath.c:36:11: fatal error: 'gmp.h' file not found
      # include <gmp.h>
                ^~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

**Comment by proycon** [comment]
You reported something similar in 2018 and found the solution at the time: #130  ... That probably works again?

**Comment by antalvdb** [comment]
It does; 

env "CFLAGS=-I/usr/local/include -L/usr/local/lib" pip install pycrypto

awkwardly does the trick on my machine. Thanks for the memory jog.
