### ISSUE TITLE
Codemetapy on macOS 12.4 unrecognized argument --with-entrypoints

### ISSUE THREAD

**Issue by antalvdb** [proycon/LaMachine#217]
[lamachine-stable-20220520_161607.log](https://github.com/proycon/LaMachine/files/8740846/lamachine-stable-20220520_161607.log)

**Comment by proycon** [comment]
Oops, I thought I had set LaMachine to use the previous version of codemetapy rather than the latest one which introduces some backward-incompatible changes. I'll take a look.

**Comment by proycon** [comment]
This is now solved!
