### ISSUE TITLE
LaMachine breaks on CentOS 7 (and possibly others) due to icu >=52 requirement

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#30]
Our newest libfolia requires a version of icu that CentOS 7 (and possibly other conservative distros) does not ship yet. This hurts compatibility and we should look into it.

**Comment by proycon** [comment]
(Latest icu version on CentOS 7 is currently 50)

**Comment by kosloot** [comment]
version 50 is very old:
Release Date: 2012-12-17, so CentOS is broken imnho

version 52 was chosen as being the most recent version available on Ubuntu 14 AND supporting pkg-config.
Maybe 50 will also work. Can you please check this on CentOS?

BTW: this change is from may 8 2017.  Why took it so long to signal any problems?

**Comment by proycon** [comment]
We don't have any automated CentOS tests unfortunately, my last test must have predated this. There's also not that many CentOS users for LaMachine I guess.

I'll do a test to see if libicu 50 works with libfolia.

**Comment by proycon** [comment]
libfolia works with libicu 50, the whole stack compiles fine.

**Comment by kosloot** [comment]
reverted the condition to use ICU version 50
