### ISSUE TITLE
[lamachine2] Add kaldi to LaMachine

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#32]
(partially done for VM/docker already, to be tested, still to do for virtualenv)

**Comment by proycon** [comment]
(in progress but not finished yet)

**Comment by proycon** [comment]
This is now planned for lamachine v2, as discussed also with @vanlummelhuizen , @schemreier, @ltenbosch et al..

                      De belangrijkste uitkomst is dat we voor Kaldi op Ponyland gebruik gaan                                                                                                  
                      maken van de Kaldi in LaMachine-v2                                                                                                                                       
                      (https://github.com/proycon/LaMachine/blob/lamachine2/lamachine_v2_plan.md).                                                                                             
                      Dat betekent dat de globaal geïnstalleerde Kaldi altijd een recente                                                                                                      
                      versie is die geupdate wordt wanneer LaMachine geupdate wordt. Als je                                                                                                    
                      een specifieke Kaldi-versie (of eigenlijk een specifieke git-commit) wil                                                                                                 
                      gebruiken, dan kan je dat in een LaMachine-build-script aangeven zodat                                                                                                   
                      je in een lokaal geïnstalleerde/gecompileerde LaMachine de                                                                                                               
                      gespecificeerde Kalde-versie hebt.

**Comment by proycon** [comment]
* https://github.com/UFAL-DSG/alex-asr should be explicitly included as well

**Comment by proycon** [comment]
This relies our adaptations of the Kaldi-NL repository (https://github.com/opensource-spraakherkenning-nl/Kaldi_NL) being available on github. Big downloadable models should be stored separately and retrievable with e.g. a ``download.sh`` script.
                                                                                                                                                                                            
>   Verder wordt door mij (Micha) en Mario bekeken hoe we de wijzigingen en                                                                                                  
>   toevoegingen aan Kaldi-egs in git-repositories kunnen onderbrengen.                                                                                                      
>   Maarten stelde voor om de Kaldi_NL repository te forken en deze te delen                                                                                                 
>   met gebruikers binnen CLST. Voor andere egs/recipes kan dan een andere                                                                                                   
>   git-repository worden aangemaakt. Het kan wenselijk zijn een                                                                                                             
>   Github-groep voor CLST te maken. Het beheer van deze nieuwe en geforkte                                                                                                  
>   repositories zal bij de Technical Support Group komen te liggen. Op                                                                                                      
>   Github is het mogelijk om met behulp van issue-tracking, te overleggen                                                                                                   
>   over de scripts/recipes. Dit zou de commentfunctionaliteit op                                                                                                            
>   https://www.cls.ru.nl/clst-asr/ (deels?) onnodig maken.

**Comment by proycon** [comment]
Ok, we have a first functioning version of kaldi in LaMachine v2 now.

@vanlummelhuizen , @schemreier, @ltenbosch : Is there any progress regarding the 'gitification' of the Kaldi_NL and other resources?

**Comment by vanlummelhuizen** [comment]
(sorry for the late reply)

Great! We are still struggling to get things running from outside a Kaldi installation. Hopefully we have some progress this afternoon, so that we can also test Kaldi in LaMachine.

Kaldi_NL itself is already in Github: https://github.com/opensource-spraakherkenning-nl/Kaldi_NL . As soon as a project correctly using Kaldi_NL and in turn Kaldi, we will gitify it, but perhaps not on Github.

**Comment by proycon** [comment]
@vanlummelhuizen , @schemreier, @ltenbosch: Alex-ASR proves to be more difficult than anticipated. The problem is that it is tied to a specific kaldi version which its installation procedure pulls in and compiles (disabling cuda support by the way). I attempted to compile alex-asr against the latest kaldi that LaMachine provides, but it seems alex-asr isn't compatible enough and I have to make changes in it for it to work. I'm a bit reluctant to edit upstream software, but I also don't like the idea of having alex-asr not use the main kaldi installation but another outdated one. Perhaps this is something to take up with the upstream author, though the project does not seem not very active these days.

**Comment by proycon** [comment]
I spoke to Mario a while back and decided to keep alex-asr out of LaMachine for now; kaldi itself is included of course.

As for the  'gitification' of Kaldi_NL and other resources, let's continue that in follow-up issue.
