### ISSUE TITLE
docker startwebservices doesn't work

### ISSUE THREAD

**Issue by matthijsbrouwer** [proycon/LaMachine#34]
Creating clam webservices with
`docker run -p 8080:80 -t -i proycon/lamachine`
and then starting them with
`/usr/src/LaMachine/startwebservices.sh`
doesn't work, no service available on port 8080.
On testing nginx with
`nginx -t`
I did get
`2018/01/26 13:43:15 [emerg] 6#6: getpwnam("http") failed`
When a user 'http' is added with
`useradd --no-create-home http`
before the call to `startwebservices.sh`, at least ucto, frog, timbl and colibri-core seem to work

**Comment by proycon** [comment]
Thanks for the report and the solution! I guess something must have changed in the Arch image we base on, I added an attempted fix in the development branch, will merge into master soon.

**Comment by proycon** [comment]
(now obsolete because of LaMachine v2 release)
