### ISSUE TITLE
crossdomain problem localhost/127.0.0.1

### ISSUE THREAD

**Issue by matthijsbrouwer** [proycon/LaMachine#35]
Using the webservices with docker on port 8080, for example frog, when using url 
`http://localhost:8080/frog`
the reference to the stylesheet is
`<?xml-stylesheet type="text/xsl" href="http://127.0.0.1:8080/frog//static/interface.xsl"?>`
causing cross-domain problems. On Firefox 57.0.4:
`Error loading stylesheet: An unknown error has occurred (805303f4)`
Everything works when instead url
`http://127.0.0.1:8080/frog`
is used. It would be nice if the url for the stylesheet uses the domain name used in the request.

**Comment by proycon** [comment]
Yes, this is indeed a known issue in CLAM. The host has to match exactly or browsers refuse to load stylesheets. I'll have to investigate whether I can make things more flexible, depending on to what extent browsers adhere to cross-domain origin headers for the loading of XSL stylesheets.

**Comment by proycon** [comment]
Continued in proycon/clam#63, closing here....
