### ISSUE TITLE
problem with using  ticcl.nf  with polish and english lexicon in Docker relase

### ISSUE THREAD

**Issue by mathias3** [proycon/LaMachine#37]
Might be problem with reading .txt stead of folia.xml

`nextflow run LanguageMachines/PICCL/ticcl.nf --inputdir /home/projects/Kaggle_denoise/ICDAR-2017-Post-OCR-Correction/text/ --lexicon data/int/pol/pol.aspell.dict --alphabet data/int/pol/pol.aspell.dict.lc.chars --charconfus data/int/pol/pol.aspell.dict.c0.d2.confusion --inputtype 'text'

N E X T F L O W  ~  version 0.27.4
Launching `LanguageMachines/PICCL` [mad_legentil] - revision: a006ed747c [master]
NOTE: Your local project version looks outdated - a different revision is available in the remote repository [e9754ef2e1]

TICCL Pipeline

[warm up] executor > local
[f4/ce2b3e] Submitted process > txt2folia (1)
[3f/e17ce8] Submitted process > corpusfrequency (1)
ERROR ~ Error executing process > 'corpusfrequency (1)'

Caused by:
  Missing output file(s) `corpus.wordfreqlist.tsv` expected by process `corpusfrequency (1)`

Command executed:

  set +u
  if [ ! -z "" ]; then
      source /bin/activate
  fi
  set -u
  
  FoLiA-stats --class "OCR" -s -t 1 -e folia.xml --lang=none --ngram 1 -o corpus .

Command exit status:
  0

Command output:
  start processing of 1 files 
  done processsing directory '.'
  start calculating the results
  in total 0 n-grams were found.

Command error:
  
  XML-error: PCDATA invalid Char value 12
  
  FoLiA-stats: failed to load document './doc.folia.xml'
  FoLiA-stats: reason: XML error: No XML document read

Work dir:
  /usr/src/LaMachine/work/3f/e17ce8cb5ee9d497957609b34fdc29

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details`

**Comment by mathias3** [comment]
additionally  ocr.nf also does not work for language pol - I traied to download different versions of  pol.traineddata (no idea which tesseract version LaMachine uses) with no luck 

`Caused by:
  Process `tesseract (1)` terminated with an error exit status (1)

Command executed:

  tesseract ifs_20171025_0000015824124S_105-001-000.tif ifs_20171025_0000015824124S_105-001-000 -c "tessedit_create_hocr=T" -l pl

Command exit status:
  1

Command output:
  (empty)

Command error:
  Error opening data file /usr/share/tessdata/pl.traineddata
  Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
  Failed loading language 'pl'
  Tesseract couldn't load any languages!
  Could not initialize tesseract.

Work dir:
  /usr/src/LaMachine/work/71/4a9e48ff941477c6911a88ce4a65c8

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
`

**Comment by proycon** [comment]
Good point.. LaMachine currently only installs a few tesseract models by default (installing all would be a bit large), please run a ``pacman -Syu tesseract-data-pol`` inside the container to explicitly install the polish models.  Also set ``--language pol`` (not ``pl``) when invoking ``ocr.nf``.

**Comment by proycon** [comment]
Your original issue looks like a problem in processing plain text rather than  FoLiA indeed, or a conversion problem. I moved the issue to LanguageMachines/PICCL#23 .
