### ISSUE TITLE
Changed libraries on ubuntu 17.10

### ISSUE THREAD

**Issue by bloemj** [proycon/LaMachine#39]
I just tried to install LaMachine (the latest stable version, I assume) on a mostly fresh install of Ubuntu 17.10. It works, but the included list of dependencies don't all exist any more. I had to change the following ones to make it install:

libgnutils-dev -> libgnutils28-dev
libatlas-dev -> libatlas-base-dev

I also got an error due to not having virtualenv.

After manually installing the following list of dependencies, the bootstrap script got things running, passing all tests:

pkg-config git-core make gcc g++ autoconf automake autoconf-archive libtool autotools-dev libicu-dev libxml2-dev libxslt1-dev libbz2-dev zlib1g-dev libtar-dev libaspell-dev libhunspell-dev libboost-all-dev python3 python3-dev python3-pip python3-virtualenv libgnutls28-dev libcurl4-gnutls-dev wget curl libexttextcat-dev libatlas-base-dev libblas-dev gfortran libsuitesparse-dev libfreetype6-dev myspell-nl perl default-jre tesseract-ocr tesseract-ocr-eng tesseract-ocr-nld tesseract-ocr-deu tesseract-ocr-deu-frak tesseract-ocr-fra poppler-utils djvulibre-bin libdjvulibre-text imagemagick virtualenv

**Comment by proycon** [comment]
Won't be fixed in LaMachine v1 anymore but will be in upcoming LaMachine v2 (see also #41)
