### ISSUE TITLE
[lamachine2] Include custom version support

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#51]
(Reimplementation of #17)

**Comment by proycon** [comment]
Requested by INT (#72)

**Comment by pdekker12** [comment]
What is the status of the "version pinning"? For us, it would be very convenient to have, when we want to install and update PICCL on a production server on production hardware in the coming months. Let me know when there is more news :)

**Comment by proycon** [comment]
Will do, it's on my radar but I haven't gotten to it yet, I hope I can make some progress this week.

**Comment by proycon** [comment]
Users should be aware that the custom versioning that is being implemented is limited, it only pertains to software that is 1) not provided by the linux distribution itself, and 2) explicitly installed by LaMachine, rather than dependencies that are pulled in automatically by package managers. Even then, certain software is excluded from this scheme as the upstream provider does not provide the necessary facilities for obtaining older versions, LaMachine should output a warning in the log if that is the case.

**Comment by proycon** [comment]
First version of custom versioning is implemented (but is limited as stated already), so I am closing this issue. However, the implementation still requires more testing in actual use cases so new issues will probably arise. Current weak points/limitations are:

* Custom versioning on MacOS is not supported (and probably won't be supported in the future either unless there is a huge demand)
* Custom versioning necessarily excludes packages supplied by the linux distribution's package manager. To ensure getting a LaMachine environment close to the original, ensure you build it on the same distribution.
* Versioning of java/maven software is not supported yet (but will be in the future)
* Some software is excluded as either upstream doesn't provide the necessary release history, or it needs more effort on my part to support that release history as it deviates from the default, examples are: Nextflow, Alpino
* Testing of custom versioning has still been fairly limited

**Comment by pdekker12** [comment]
@JessedeDoes @jan-niestadt
