### ISSUE TITLE
Fresh installation failed on Windows 10 (vagrant + downloaded zip)

### ISSUE THREAD

**Issue by amussche** [proycon/LaMachine#58]
I downloaded the latest lamachine zip file on Windows 10 and started it by using Vagrant.
After booting and installation it gives an "fatal error".
After login with ssh, frog etc is not installed.

**Comment by amussche** [comment]
[lamachine-frog.txt](https://github.com/proycon/LaMachine/files/1832344/lamachine-frog.txt)

**Comment by amussche** [comment]
Sounds good to me, please give me signal when I can test it

Van: Maarten van Gompel <notifications@github.com>
Verzonden: woensdag 21 maart 2018 11:30
Aan: proycon/LaMachine <LaMachine@noreply.github.com>
CC: André Mussche <a.mussche@ultraware.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [proycon/LaMachine] Fresh installation failed on Windows 10 (vagrant + downloaded zip) (#58)


Confirmed, something must have broken very recently, the upgrade of the underlying distribution fails. I'm planning to release the new LaMachine v2 this week, so I'd rather not fix the current one but would recommend you try that when it comes out. Is that okay?

**Comment by proycon** [comment]
There is a prelease of LaMachine v2 available now, see https://github.com/proycon/LaMachine/issues/61 . If you are willing to give it a try: follow the installation instructions under subsection C in https://github.com/proycon/LaMachine/blob/lamachine2/README.md (this is assuming you want to run on Windows with a VM)

**Comment by proycon** [comment]
(Closing this as quite some time has passed, please reopen if still relevant)
