### ISSUE TITLE
how to run frog through virtual box?

### ISSUE THREAD

**Issue by edmondr** [proycon/LaMachine#6]
Hey,

Ive been trying to get the LaMachine to work, but i cant figure out the install instructions. I'm running windows, and downloaded vagrant & virtual box.

Do I
1) boot up virtual box and install ubuntu,
2) run the $ git ... && laMachine in terminal
3) ??
4) profit

Honestly i'm completely lost. 

Do I boot up the terminal in virtualbox (can i do that)? Does LaMachine run inside the virtualbox or do i need to install an operating system first? 

If you could provide a detailed guide, or at least a couple more pointers, would be forever grateful.

**Comment by proycon** [comment]
No, you don't need to install a linux distro (LaMachine does that for you).
I guess you got stuck on the third instruction, which was formulated in a rather unix-oriented fashion:

3) Clone this repository and navigate to the directory in the terminal: ``$ git clone https://github.com/proycon/LaMachine && cd LaMachine`` (or download the ZIP manually from github)

You will have to obtain a copy of the latest LaMachine from github and then navigate to the directory where you put it **in the Windows Command Prompt** (i.e. the Windows equivalent of a terminal), once there issue the commands ``vagrant up`` and afterwards ``vagrant ssh`` as per instructions four and five. Those will set up the virtual machine from scratch automatically.

**Comment by edmondr** [comment]
Yes! That's exactly it. Thank you very much :)
