### ISSUE TITLE
Installation fails on activation of control virtualenv if the previous build failed

### ISSUE THREAD

**Issue by Duchadian** [proycon/LaMachine#62]
On Ubuntu 16.04 Server

previous build failed on a .yml config file

Reusing existing control environment...
/proc/self/fd/11: line 935: ./bin/activate: No such file or directory
================ FATAL ERROR ==============
An error occurred during installation!!
Unable to activate LaMachine controller environment

**Comment by proycon** [comment]
Does the error go away if you remove the yml files and the directory ``lamachine-controller`` ?

**Comment by Duchadian** [comment]
Yes. That seems to be a fix.

**Comment by proycon** [comment]
I think I just found and fixed the cause
