### ISSUE TITLE
[LaMachine 2] bootstrap fails on: A recursion loop was detected with the roles specified. 

### ISSUE THREAD

**Issue by kosloot** [proycon/LaMachine#65]
Opening installation file /home/sloot/git/install-LAMA.yml in editor for selection of packages to install...
Running ansible command from /home/sloot/git/lamachine-controller/LAMA/LaMachine: ansible-playbook --ask-become-pass -i /home/sloot/git/lamachine-controller/LAMA/LaMachine/hosts.LAMA install-LAMA.yml -v
Using /data/git/lamachine-controller/LAMA/LaMachine/ansible.cfg as config file
SUDO password: 
ERROR! A recursion loop was detected with the roles specified. Make sure child roles do not have dependencies on parent roles

The error appears to have been in '/data/git/lamachine-controller/LAMA/LaMachine/roles/gecco/meta/main.yml': line 3, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - { role: gecco }
    ^ here
======================================================================================
Building a local LaMachine environment has failed unfortunately. You have several options:
 - Start from scratch again with a new bootstrap, possibly tweaking configuration options
-  Attempt to activate the environment (run: lamachine-LAMA-activate) and debug the problem
-  Run lamachine-LAMA-update after activating the environment to see if the problem corrects itself
 - File a bug report on https://github.com/proycon/LaMachine/issues/

**Comment by proycon** [comment]
There was a bug in the gecco package indeed, I fixed it now.
