### ISSUE TITLE
[LaMachine 2] Bootstrap fails during installation of PICCL

### ISSUE THREAD

**Issue by kosloot** [proycon/LaMachine#66]
TASK [piccl : Download data and example corpora for PICCL] ********************************************************************
fatal: [lamachine-LAMA]: FAILED! => {
    "changed": true, 
    "cmd": "if [ ! -d data ]; then\n ./download-data.nf\n fi\n if [ ! -d corpora ]; then\n ./download-examples.nf\n fi", 
    "delta": "0:00:00.002302", 
    "end": "2018-03-27 11:35:52.260330", 
    "rc": 127, 
    "start": "2018-03-27 11:35:52.258028"
}

STDERR:

/usr/bin/env: ‘nextflow’: No such file or directory
/usr/bin/env: ‘nextflow’: No such file or directory

MSG:

non-zero return code
[lamachine-LAMA.log](https://github.com/proycon/LaMachine/files/1851366/lamachine-LAMA.log)

**Comment by kosloot** [comment]
The system advises:
``to retry, use: --limit @/data/git/lamachine-controller/LAMA/LaMachine/install-LAMA.retry``

but this is not helpfull

**Comment by proycon** [comment]
Hmm, yes, that retry message is an ansible thing which is indeed not very helpful, I'll have to see if I can surpress it somehow.

**Comment by proycon** [comment]
Solved
