### ISSUE TITLE
Option to make installer append path export to .zshrc instead of .bashrc

### ISSUE THREAD

**Issue by Duchadian** [proycon/LaMachine#68]
Title is pretty self-explanatory. 

This may already be in the installer, but I couldn't find it. Maybe include it in the install-lm.yml?

**Comment by Duchadian** [comment]
On second thought, install-lm.yml probably isn't the right place..

**Comment by proycon** [comment]
right, good idea.. I'm using zsh myself too even, I'll have it autodetect whether a .zshrc is present, the change is only minimal anyway (only ~/bin).

**Comment by Duchadian** [comment]
Another option is to have the user enter the location of the preferred file, with the default being ~/.bashrc. That would also ensure compatibility for users that use something else than bash or zsh (or have a central config for both).

**Comment by proycon** [comment]
Other shells (csh, tcsh, ksh, whatever) tend to have quite a different syntax (not bash compatible), so they'd have to be explicitly supported, which we don't now (and there's no demand for it yet anyway)
