### ISSUE TITLE
[LaMachine2] No obvious way to bootstrap locally into custom directory

### ISSUE THREAD

**Issue by zeusttu** [proycon/LaMachine#73]
There appears to be no obvious way to choose where to install LaMachine in case of a local virtualenv install using the `bootstrap.sh` script. Is there a way to have the LaMachine virtual environment created in a custom location? If not, can it be safely moved to a custom location afterward? (I am not sure if virtual environments contain hardcoded paths.)

### What do I expect to happen?

Looking at the bootstrap script, it looks like it should create an environment somewhere in the `$BASE_DIR`, which looks like it should default to the current working directory (`$(pwd)`). So if I change directory prior to the bootstrap, I would expect the virtual environment to be created as a child directory of my working directory.

Alternatively I would expect a command-line parameter to specify where I want the environment to be created.

For reference, the command I run is:

    {{lamachine_repo}}/bootstrap.sh --flavour local --version stable --env virtualenv --name {{venv_name}} --install piccl --private --noninteractive

### What happens instead?

The `lamachine-{{environment_name}}` directory with the virtual environment is consistently made in `$HOME/lamachine-{{venv_name}}`. Note that my present working directory at that moment is neither the home directory nor a parent or child directory of the home directory.

### What else have I tried?

I also tried to check out the repo in the desired base directory and specify its path with `--source {{desired_base_directory}}` but to no avail.

### System details

Mostly barebones CentOS 7 in a Vagrant box (not based on your Vagrant file, rather we initialize it barebones and provision it with our own Ansible script, which in turn checks out the LaMachine repository and runs its bootstrap script.)

**Comment by proycon** [comment]
Good point, thanks for your report! The bootstrap procedure does ask where you want the local environment, but this is skipped in non-interactive mode and a parameter flag was indeed missing; I'll add one right away and will update here!

As to your system setup; calling bootstrap from within your own ansible script is of course possible (I see where you are coming from replacing the old ``virtualenv-bootstrap.sh``), but LaMachine v2 also offers a more direct way (bootstrap interactively once and choose the *remote* flavour), in which case the LaMachine ansible script would form the foundation which you yourself can expand. This is eventually what I'd recommend.

**Comment by proycon** [comment]
I now added ``--targetdir`` option to ``bootstrap.sh`` which should do what you need. (It's in the ``develop`` git branch, I'll merge into master soon and also do the formal v2.1 release at the end of the day probably).

I see I forgot to answer you other question: the virtual environment indeed contains hard coded paths and can not be simply moved.

**Comment by proycon** [comment]
This has been merged into master now so the issue should be solved (please reopen if unexpected problems occur)

**Comment by zeusttu** [comment]
Thank you a lot! I think I will at least initially use the old way of installing because that is the least invasive to our current install workflow (currently we already have a working install workflow based on LaMachine v1 which I am trying to port as much as-is as possible to LaMachine v2), but afterward we may look into the remote install option too and see what benefits it has :slightly_smiling_face: 

One thing: I still see the virtual environment being created in `~/lamachine-{{env_name}}` instead of in the specified target directory. I looked a bit more thoroughly in the bootstrap script and the LaMachine playbook and found that the bootstrap script does not end up writing the `local_prefix` because the `locality` variable is never set. I worked around this by setting `locality=local` in my environment before calling the bootstrap script, which seems to work :smile:

**Comment by proycon** [comment]
Ah, thanks! good catch! That is a bug indeed (should be ``$LOCALITY``), I wonder how it passed the tests like that..

Yeah, I understand the path you're taking to integrate it into what you have already; just wanted to make sure the new remote flavour was at least known :)
