### ISSUE TITLE
Simple software metadata registration

### ISSUE THREAD

**Issue by proycon** [proycon/LaMachine#74]
LaMachine manages the installation of heterogeneous types of software, i.e. from different repositories and written in/for different languages. These tend to have different types of metadata associated with them. 

LaMachine already attempts to provide a simple overview of the software it has installed (``lamachine-list``), which explicitly the lists the version that has been installed. This is needed for several reasons:

 * To give the end-user an overview of installed software
 * To provide any kind of portal function later on
 * To ensure exact versions can be logged for scientific reproducibility
   * To ensure a LaMachine custom verison installation can be build on the basis of those version (not implemented yet)
 * Especially software version information is important for the WP3 VRE project for exact registration of 
provenance (@menzowindhouwer), higher level tools such as CLAM do not provide the necessary details (versions of wrapped software are not exposed and there is no mechanism to reliably do so currently). I think dependency information is similarly important, as the version of the dependencies of a software package may just as well affect the whole and can therefore be just as relevant for the overall 'fingerprint'.

To make software metadata usable, we need a common metadata model and a conversion module to convert data from various repositories (e.g. Debian/RedHat/Arch/AUR/Homebrew, PyPI, Maven, CPAN, CRAN,  F-Droid/Google Play, Apple store) to a common model. 

I strongly believe that software metadata should live as close to the source as possible, because the further away it is, the harder it is to maintain and the most likely it is to diverge from the actual software (and thus not describe it accurately anymore). The best cases are:

1) Software metadata is *provided by the software authors* and lives right along and is *distributed with the source code* (or binary if need be) in the source code repository and any releases. 
2) Software metadata is *provided by the software authors* in the repositories that hold the release (PyPI, Maven Central, Linux distribution's package manager)

Getting to the less desirable cases:
3) Metadata is manually provided in LaMachine (in the installation recipes). This is currently done for some software but is sub-optimal and only done in the absence of 1 and 2. 
4) Metadata is manually compiled, possibly even by an external party, and is deposited somewhere detached from the software (I think this what was attempted in a CLARIAH project by Utrecht University). This is the least desirable scenario in my view and only make sense for additional higher-level/domain-specific metadata that can not be properly harvested.

One of the challenges is the heterogeneous nature of the metadata. I propose we adhere to scenarios 1 and scenario 2 as much as possible (often they are tied anyway, consider the ``setup.py`` of a Python project which PyPI uses or a ``pom.xml`` in the Java/Maven world) . LaMachine would automatically and dynamically harvest established metadata descriptions at build time and convert these to some common representation (not entirely trivial of course). Existing software metadata initiatives such as [DOAP](https://en.wikipedia.org/wiki/DOAP) and [ADMS.WS](https://joinup.ec.europa.eu/svn/adms_foss/adms_sw_v1.00/adms_sw_v1.00.htm#Software%20Project%20-%20release) may serve as a foundation or at least inspiration for a common model, ensuring we don't reinvent the wheel and may later find rapprochement if we ever go the full formal semantic web route.

The common representation should be simple enough to be widely usable and should hold at least all the information necessary for our objectives (LaMachine & VRE). For the VRE's provenance tracker, a simple API endpoint could be added to LaMachine, allowing it to obtain software versions and further metadata.

**Comment by proycon** [comment]
Small follow up to prevent confusion: This idea applies to the more basic metadata of software; the VRE (and perhaps even LaMachine too) may require more elaborate specifications on how to invoke software that goes beyond what I consider metadata here and needs specialised descriptions (like the CMDI in the VRE demo @menzowindhouwer showed me) .

**Comment by proycon** [comment]
This seems an interesting initiative that we could use: https://github.com/codemeta/codemeta

**Comment by kosloot** [comment]
Yeah, but trafic is low there.
Lots of open issues and 2 pull requests that seem to be ignored.

**Comment by proycon** [comment]
I'm continuing the metadata effort as a separate tool in: https://github.com/proycon/codemetapy
