### ISSUE TITLE
Bootstrap with --version stable installs latest Piccl master

### ISSUE THREAD

**Issue by zeusttu** [proycon/LaMachine#75]
When the bootstrap script is run with `--version stable`, it is supposed to install the latest stable (tagged) version of each Language Machine, but for Piccl it turns out to check out the `master`-branch instead. I tracked this down to the `lamachine-python-install` role which largely overwrites the work done by the `lamachine-git` role. (The `lamachine-git` role does neatly check out the latest stable/tagged version.)

I have fixed this locally so you can expect a pull request shortly.

**Comment by proycon** [comment]
That indeed was a bad oversight! Thanks for fixing it!
