### ISSUE TITLE
Condition cannot be evaluated if webserver != nginx

### ISSUE THREAD

**Issue by zeusttu** [proycon/LaMachine#86]
https://github.com/proycon/LaMachine/blob/ae3bb5c23f585077249c40bee0b55d41aa86dd28/roles/lamachine-core/tasks/webserver.yml#L142

Because the condition starts by checking the return code of a command that has been skipped, it raises an error. I would suggest rewriting the condition to:
```ansible_distribution|lower != "macosx" and webservertype == "nginx" and nginx.rc != 0```
so that the part of the condition that checks the return code is only evaluated if the same conditions are met as those for running the command, ensuring that the condition will not be evaluated if it would raise the error.

(Putting the solution right here in the issue seems like it may be faster than getting a pull request merged because it's a really small change so that's why I'm doing it this way.)

**Comment by proycon** [comment]
Right! Fixed in above commit!

**Comment by zeusttu** [comment]
Any indication how long it will take for this to end up in the master branch? It seems LaMachine itself clones and pulls the repository several times so it's difficult to perform a test run when the commit is not in the master branch yet :sweat_smile:

**Comment by proycon** [comment]
Ah yes, I merged it into the development branch first as I usually do (which contains some more unrelated changes that I still have to test), but I cherry-picked this fix into the master branch now so you can use it immediatelely.

**Comment by zeusttu** [comment]
Thank you! :smiley:
