### ISSUE TITLE
Git issue when re-installing LaMachine with new releases of packages

### ISSUE THREAD

**Issue by pdekker12** [proycon/LaMachine#88]
On a LaMachine server, which I installed a while ago, I try to do a new Ansible install of LaMachine, in order to upgrade the supplied software packages. The re-installation goes fine for most packages, but fails for packages were files have been renamed or removed since the last release.

I get the following git error for mbt:

```
"STDERR:", "", "error: The following untracked working tree files would be overwritten by checkout:", "\tREADME", "Please move or remove them before you can switch branches.", "Aborting", "", "", "MSG:", "", "non-zero return code", "", "TASK [lamachine-git : mbt - STASHING AWAY LOCAL CHANGES!!!] ********************", "fatal: [svatpi01.ivdnt.loc]: FAILED! => {", "    \"changed\": true, ", "    \"cmd\": \"echo \\\"There appear to be local changes, LaMachine will stash them away\\\">&2\\n echo \\\"this means they are not deleted and recoverable in principle,\\\">&2\\n echo \\\"but they are NOT used in this compilation. You should \\\">&2\\n echo \\\"git add them properly if you want to use any custom changes\\\">&2\\n echo \\\"... allowing for 15 second grace period (CTRL-C in case of panic)...\\\"\\n sleep 15\\n git stash -u\", ", "    \"delta\": \"0:00:15.162171\", ", "    \"end\": \"2018-05-24 12:41:51.608180\", ", "    \"rc\": 1, ", "    \"start\": \"2018-05-24 12:41:36.446009\"", "}", "", "STDOUT:", "", "... allowing for 15 second grace period (CTRL-C in case of panic)...", "", "", "STDERR:", "", "There appear to be local changes, LaMachine will stash them away", "this means they are not deleted and recoverable in principle,", "but they are NOT used in this compilation. You should ", "git add them properly if you want to use any custom changes", "", "*** Please tell me who you are.", "", "Run", "", "  git config --global user.email \"you@example.com\"", "  git config --global user.name \"Your Name\"", "", "to set your account's default identity.", "Omit --global to set the identity only in this repository.", "", "fatal: empty ident name (for <dekker@svatpi01.ivdnt.loc>) not allowed", "Cannot save the current index state", "", "", "MSG:", "", "non-zero return code", "", "PLAY RECAP *********************************************************************", "svatpi01.ivdnt.loc         : ok=247  changed=142  unreachable=0    failed=2   ", "", "======================================================================================", "\u001b[1m\u001b[31mBuilding a local LaMachine environment has failed unfortunately.\u001b(B\u001b[m You have several options:", " - Retry the bootstrap, possibly tweaking configuration options", " - Attempt to activate the environment (run: lamachine-lamachine-activate) and debug the problem", " - Run lamachine-lamachine-update after activating the environment to see if the problem corrects itself", " - File a bug report on https://github.com/proycon/LaMachine/issues/", "   The log file has been written to /vol1/lamachine-controller/lamachine/LaMachine/lamachine-lamachine.log"]}
	to retry, use: --limit @/home/peter/git/piccl/Piccl.retry
```

The file README, which has been removed since the last release, is now redundant and seen as a local change.

A solution may be to remove all source repositories in /vol1/lamachine/src at the start of the installation. When I do this manually, the installation finishes without problems.

**Comment by pdekker12** [comment]
Related to this: to facilitate an update of an existing installation, it would also be nice if the /vol1/lamachine/bin directory would be cleaned during the installation.

If a file is renamed or deleted since the last install (in this case dbnl.nf), there is still a symlink in the /vol1/lamachine/bin directory, but it points to a location that does not exist anymore.

**Comment by proycon** [comment]
Ok, looking at the output, this appears to happen because the git stash fails because no git identity was configured (a contingency I hadn't considered yet):

```
fatal: empty ident name (for <dekker@svatpi01.ivdnt.loc>) not allowed
```

Let's see if I can find an elegant solution for that..

**Comment by proycon** [comment]
About cleaning; I don't really want to forcibly clean everything by default, but I can make this an option, that might be a nice addition. Cleanup is currently still something to work on (see also #79), it often makes less sense to clean inside an existing LaMachine as it's often easier to just build a new LaMachine from scratch.

**Comment by pdekker12** [comment]
Cleaning as an option would be nice. It would be convenient to have it as an option on bootstrap.sh, since that is what we call in our installation script.

For us, updating LaMachine (or at least having the possibility) is preferable over a full re-install, because it appears to be faster.

**Comment by proycon** [comment]
Yeah, agreed, updating is always preferable (except if you want to delete stuff/downsize LaMachine, or things have gotten too cluttered).

I now added something (*not in master branch yet* though, will need more tests first). You can add a ``force=2`` parameter for ``lamachine-update`` (from within LaMachine); or a ``--force 2`` to ``bootstrap.sh`` on the *initial* bootstrap, which sets ``force: 2`` in your configuration file (you can do that manually if it's not the first bootstrap).

The values of force:
* 1 - Forces all software to recompile, even if no upstream update is available, git stashes away any possible changes you may have made yourself (so not technically deleted)
* 2 - Bluntly deletes everything in the source directory (except LaMachine itself), this still doesn't include the ``bin/`` dir and others, as cleaning those would be too problematic.

Do note that using this will slow down stuff significantly again, as everything has to be redone, so you lose a big part of the update advantage over reinstalling.

**Comment by pdekker12** [comment]
Thanks, this sounds like a good option! Why is it problematic to clean ``bin/`` and others? Is this also a risk if I do it manually?

**Comment by proycon** [comment]
My test passed so I merged it into master now. Some other directories like ``var/`` might contain user-generated files which I wouldn't want to wipe.  ``bin/`` might be problematic if the python interpreter there is used and deleted. 

Can you test if this now fixes the git error you had?

**Comment by pdekker12** [comment]
I tested the Ansible script on an another server which also had a (different) old LaMachine installation. There were no git errors at all during the installation, so I think the fix works! I only had to remove one file manually: /vol1/lamachine/bin/dbnl.nf

This was even without the force option. Unfortunately, I was not able to test the force option (on an existing installation). I do not have direct access to the configuration file in the folder of the LaMachine repository, since the LaMachine repo is downloaded and afterwards deleted by our Ansible script.

**Comment by pdekker12** [comment]
When I made some changes to a file in a git repository, and then tried to upgrade using an Ansible script, the error re-occurred again. The `force` option was not on for this installation. This does not have high priority (I just removed directories), but thought it would be good to report.

```
TASK [piccl : Installing PICCL webservice] *************************************", "", "TASK [lamachine-python-install : PICCL - Git clone/pull latest v0.6.2] *********", "fatal: [svatpi03]: FAILED! => {", "    \"before\": \"b5823d65e7a590313ae10681d441a30e5880d4fc\", ", "    \"changed\": false", "}", "", "MSG:", "", "Local modifications exist in repository (force=no).", "", "PLAY RECAP *********************************************************************", "svatpi03                   : ok=426  changed=177  unreachable=0    failed=1   ", "", "======================================================================================", "\u001b[1m\u001b[31mBuilding a local LaMachine environment has failed unfortunately.\u001b(B\u001b[m You have several options:", " - Retry the bootstrap, possibly tweaking configuration options", " - Attempt to activate the environment (run: lamachine-lamachine-activate) and debug the problem", " - Run lamachine-lamachine-update after activating the environment to see if the problem corrects itself", " - File a bug report on https://github.com/proycon/LaMachine/issues/", "   The log file has been written to /vol1/lamachine-controller/lamachine/LaMachine/lamachine-lamachine.log"]}
```

**Comment by proycon** [comment]
Should be solved now
