### ISSUE TITLE
Characters sometimes dissapear when using Frog

### ISSUE THREAD

**Issue by lyltje** [proycon/LaMachine#9]
When using lamachine (frog) I noticed that sometimes characters dissapear (in tokenization?). A few examples are:

met een kreatininespiegel tussen de 120 en de 140mmol/L.
Becomes:
met een kreatininespiegel tussen de 120 en de 140mmol L.

Berkhof, arts-assistente longziekten Berkhof arts-assistente longziekten/dr.
Becomes:
Berkhof , arts-assistente longziekten Berkhof arts-assistente longziekten dr.

Lengte 1,85m.
Becomes:
Lengte 1,8 m.

ECG: sinusritme 70 slagen per minuut, smal QRS, oud voorwandinfarct, QTc 426ms.
Becomes:
ECG : sinusritme 70 slagen per minuut , smal QRS , oud voorwandinfarct , QTc 42 ms.

cyste, astma of mengbeeld met COPD, FEV1 0.98L.
Becomes:
cyste , astma of mengbeeld met COPD , FEV1 0.9 L.

**Comment by kosloot** [comment]
You are right. 
The problem lies in the underlying tokenizer (ucto) indeed. 
We will look into that.
Thanks for reporting  this

**Comment by lyltje** [comment]
Thanks! I am looking forward to the improvement.

Best,

Lydia

**Comment by kosloot** [comment]
Closed as a lamachine Issue.
Redirected to:
https://github.com/LanguageMachines/ucto/issues/5

**Comment by kosloot** [comment]
This bug is fixed in Ucto now,

**Comment by lyltje** [comment]
Thanks for letting me know!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
