### ISSUE TITLE
Chatbot possibilities of LaMachine

### ISSUE THREAD

**Issue by DiemasMichiels** [proycon/LaMachine#92]
Hello,

Is it possible to make a fully functional chatbot in LaMachine?
For example you have Frog that understands the language and returns a FoliA XML which then can be used in...

Is it maybe possible to explain which tools I need if I want to create one with this system? Or maybe provide a quick and simple demo?

Thanks!

**Comment by proycon** [comment]
Yes, the tools available in LaMachine could be certainly used to build a chatbot. Frog will only help if it's a dutch chatbot. We don't have a particular demo, but as Python and a lot of NLP Python libraries are available in LaMachine, that's the best direction to explore.
