### ISSUE TITLE
Frog docker returns error: clamdispatcher: not found

### ISSUE THREAD

**Issue by debask** [proycon/LaMachine#95]
I've just updated my lamachine docker container and started a webserver. When accessing the Frog webserver I can create a project and add files to the project. However, when I start the project, it returns an error, while this used to work on an older version.

The error.log it returns says:
/bin/sh: 1: clamdispatcher: not found

**Comment by proycon** [comment]
Confirmed, I can reproduce this locally, will investigate..

**Comment by proycon** [comment]
(also affects the VM version)

**Comment by proycon** [comment]
Should be solved now in the latest LaMachine release (v2.2.8, available on docker hub), please update and reopen if problems persist.
