### ISSUE TITLE
Win Error 10061 : No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by maximdemey** [proycon/LaMachine#96]
Hi!

I'm trying to communicate with the Frog server on my command prompt using Python. I followed the instructions in the manual and am struggling with the following error:

```
from pynlpl.clients.frogclient import FrogClient
port = 12345
client = FrogClient('localhost',port)
Traceback (most recent call last):

  File "<ipython-input-10-57f2c2d9203b>", line 3, in <module>
    client = FrogClient('localhost',port)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pynlpl\clients\frogclient.py", line 33, in __init__
    self.socket.connect( (host,int(port)) )

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

Before I opened python (using Spyder) I used the command: frog --skip=p -S 12345 in the vagrant ssh command prompt. I did the installation following the LaMachine instructions. This gave me the following result: 
![image](https://user-images.githubusercontent.com/38634354/41721658-ccc6ca68-7566-11e8-8e07-b04198a1c667.png)

Do you have any insight on what may be the cause of the error I am getting, other than 'firewall' as google suggests.

Thanks a lot in advance!

**Comment by kosloot** [comment]
So the Frog server seems to be running and listening...
If you are on a command line, you could try to telnet to it:

``telnet localhost 12345``

You should get:
```
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

Then enter some text, followed ``EOT`` on a singe line.
```
Dit is een test.
EOT
```

The you should see some activity in the server window AND get a result like:
```
1	Dit	dit	[dit]	VNW(aanw,pron,stan,vol,3o,ev)	0.777085	O	B-NP		
2	is	zijn	[zijn]	WW(pv,tgw,ev)	0.999891	O	B-VP		
3	een	een	[een]	LID(onbep,stan,agr)	0.999113	O	B-NP		
4	test	test	[test]	N(soort,ev,basis,zijd,stan)	0.903055	O	I-NP		
5	.	.	[.]	LET()	1.000000	O	O		
```

**Comment by maximdemey** [comment]
Thanks for the fast response!
I can confirm that is working. I just opened a second command prompt to make a connection.

![image](https://user-images.githubusercontent.com/38634354/41724520-032b5cfc-756e-11e8-8360-99420ca3266a.png)

**Comment by kosloot** [comment]
Ok, that is good news.
So the the problem might be Windows related, of some Python oddity.

Maybe you could attempt another port, instead of 12345? like 8000 or so. Just to be sure.

Waiting for @proycon to join in ...

**Comment by kosloot** [comment]
BTW, some googling revealed that 'localhost' might not be working out of the box on Windows machines
[windows10]( http://cochinoman.com/2017/10/10/re-activate-localhost-windows-10/)
[windows7](https://stackoverflow.com/questions/24340450/localhost-on-windows-7)

**Comment by proycon** [comment]
I think I see the issue, you opened the port 12345 inside the LaMachine virtual machine but are trying to connect from your host machine (the windows machine), where you are running the script (if you ran the script inside LaMachine as well you wouldn't have this issue). It is still perfectly possible, but you would need to explicitly map the port from host machine to virtual machine for this to work. You can do so in the Virtual Box interface (Virtual Box > Machine Settings > Network), or see https://www.virtualbox.org/manual/ch06.html#natforward.

**Comment by maximdemey** [comment]
Hi! Thanks again for the quick responses
Different ports didn’t do anything. I already tried that while troubleshooting. I also tried 127.0.0.1 and my real IP adress.

@proycon I will try this out on monday when I get the chance again to work on this project. If you could leave open the issue I will definitely respond whether this solution worked! 

Thanks in advance!

Maxim

**Comment by maximdemey** [comment]
Hi! 
@proycon @kosloot I just tested it out and it works like a charm!

For others:
It might be prudent to restart your pc first before opening VirtualBox in the VirtualBox VMs folder.
Go to  Virtual Box > Machine Settings > Network and under advanced you can map a new route.
As I used port 12345 inside LaMachine I entered 12345 for both the guest as host machine and entered the IP for the host machine. This is usually 127.0.0.1.

Thanks all!
The request has been solved.
