### ISSUE TITLE
VBoxManage.exe: error: VT-x is not available

### ISSUE THREAD

**Issue by LZinsmeister** [proycon/LaMachine#99]
Hi!

I am installing LaMachine on Windows using a pre-built Virtual Machine image for Vagrant. I have installed Vagrant and VirtualBox and have run the command `vagrant init proycon/lamachine && vagrant up && vagrant ssh` in the command prompt. However, running this command I get the following error:
```
[...]
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "214ed993-99a0-4085-9066-1f0485ba134b", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```
Do you have any insight in what is causing this error? 
Thank you in advance for your answer.
![capture](https://user-images.githubusercontent.com/37622588/42025056-fb0b503a-7ac3-11e8-8b61-5df3dec0f73c.PNG)

**Comment by proycon** [comment]
First make sure Hyper-V is *disabled* in Windows (Control Panel → Programs → Turn Windows features on or off → Hyper-V) ,  if that wasn't it, make sure your CPU supports VT-x (you might have to enable it in the BIOS). See http://druss.co/2015/06/fix-vt-x-is-not-available-verr_vmx_no_vmx-in-virtualbox/

**Comment by LZinsmeister** [comment]
Hi @proycon and @Duchadian, thanks for the help both of you. In the end it was different problem than you suggested since Hyper-V is disabled, and virtualization is enabled in BIOS. Apparently something went wrong with the VirtualBox installation, and therefore `vboxmanage.exe` could not run in the command prompt. But that is fixed now, so LaMachine is running.

**Comment by proycon** [comment]
Glad you managed to solve it!
